### ISSUE TITLE
Does curl package use Windows SSIP and Schannel for SSL?

### ISSUE THREAD

**Issue by sichoudh** [jeroen/curl#100]
When using curl in windows machines, it must use windows certificate store for SSL/TLS

However for this to work as per libcurl site, libcurl.lib must be build using Wind SSIP and Schannel API

How to get this done using your curl package

**Comment by jeroen** [comment]
We build against `openssl` and use the CA bundle included with the R build for windows. Thereby the behavior is consistent and compatible with  `base::download.file()` and `base::url()`. What would be the benefit of using Wind SSIP and Schannel?

PS: your question is missing some punctuation.

**Comment by sichoudh** [comment]
Hi Jeroen

On windows machines , certificates are stored in certificate manager tool and in a typical enterprise and government organization these certificate are managed by their specific IT department, we have had few customer scenarios where IT dept gave them signed certificate , however there root CA certificate may not be present in CA bundle file included as part of R, this root CA certificate was present in windows certificate store.

Workaround we gave them was to copy the root CA cert info into CA bundle file, this steps needs to be done on all client machines that uses your package.

After digging deeper, we found that libcurl can be built using Win SSPI (https://msdn.microsoft.com/en-us/library/windows/desktop/aa380493(v=vs.85).aspx) instead of Open SSL, will be the best solution for enterprise customers or anyone using windows environment.

When using libcurl libraries that are built using Win SSPI, they know how to talk to windows certificate store.

Hence need your help to build your package to use libcurl built with Win SSPI which would solve certificate issues for windows OS

Siddharth

**Comment by jeroen** [comment]
The problem is that when you build `libcurl` with `SSIP` instead of `openssl` it will break many other packages that use openssl certs. Because R code needs to be portable we build against openssl, so that things will work the same as on other platforms.

Is the problem only the CA store? Perhaps we can add something that automatically imports CA certs from Windows.

**Comment by sichoudh** [comment]
+ Sean wells

Hi Jeroen

Yes, we also had the same concerns as you had, I had a quick look a code for libcurl, I saw that most of libcurl functions are exposed as interfaces and it’s the underlying layer that uses openssl / SSIP.

We did a small workaround to use your R packages and use curl and libcurl libraries that are built using SSIP, we just replaced the libraries in with newly built one by us.
It all worked as expected, however this is not the best approach as it would be the best to build R package using SSIP.

This will affect only Windows OS, and it’s always recommended to use SSIP/Schannel protocols on windows machines.

We can have call with Sean to discuss more.

Siddharth

**Comment by jeroen** [comment]
Anther issue (besides not being able to use openssl certificates) is that it seems curl does not support http/2 when building with native SSL...

**Comment by jeroen** [comment]
I am experimenting with native ssl builds of curl. However one thing I've found is that the error messsages are very poor. Perhaps we can help to get this improved in libcurl: https://github.com/curl/curl/issues/1626

**Comment by sichoudh** [comment]
Hi Jeroen

Adding Efrat and Sean who will be more involved in this SSL work.

Is there any other email address you want to communicate instead of using GitHub?

Siddharth

**Comment by jeroen** [comment]
Sure my email is `jeroen@berkeley.edu`

**Comment by jeroen** [comment]
Are you still interested in this? We are experimenting with windows SSL but running into major problems on Windows Server 2008 which doesn't seem to support many modern HTTPS certs.

**Comment by sichoudh** [comment]
I think I had forwarded your email to Mt team ,who are working on this feature set, let me follow up with them

Thank you checking with me

Siddharth

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jeroen** [comment]
Backing out of this for now. We tried it but TLS support on older Windows versions is really poor. In particular Windows 2008 (which is what CRAN uses) does not support TLS 1.1 and TLS 1.2 which are the standard by now.

I'll make it easier to build curl against schannel as opt-n but it won't be the default unless microsoft backports TLS 1.1 / 1.2 support to Windows Server 2008.

**Comment by jeroen** [comment]
FYI the new version of `curl` is now on CRAN. You can install a secure channel version as follows:

```r
Sys.setenv(LIBCURL_BUILD = "winssl")
install.packages('curl', type = "source")
```

For the foreseeable future, the default `curl` build will use openssl for reasons mentioned above.

**Comment by ravisuhane** [comment]
Hi Jeroen,

Can curl use user certificate  which is installed on Windows OS store when server requires client certificate for mutual authentication?

**Comment by jeroen** [comment]
Try:
```
Sys.setenv(LIBCURL_BUILD="winssl")
install.packages('curl', type = "source")
```

**Comment by ravisuhane** [comment]
thanks for your reply. let me give you more info:
In our deployments, users certificate (private key) will be stored in OS store / smart card which can not be exported.  So, we can not provide private key to curl module. User will be provided an option to select one of the certificate available in Windows OS certificate store.  

What are the API to provide User selected cert context to curl module ?
Or is there any callback method from which can be used to provide the certificate context (of user selected cert).

**Comment by jeroen** [comment]
Have you tried the thing above?

**Comment by ravisuhane** [comment]
I may be wrong but I think whatever you suggested is will enable curl to use winssl instead of openssl.
That is fine. But once I have compiled it , how can I tell curl to use one of the certificate installed on system.  I did not find any curl interface to do that also I saw following code in schannle.c

/* If the server has requested a client certificate, attempt to continue
       the handshake without one. This will allow connections to servers which
       request a client certificate but do not require it. */
    if(sspi_status == SEC_I_INCOMPLETE_CREDENTIALS &&
       !(connssl->req_flags & ISC_REQ_USE_SUPPLIED_CREDS)) {
      connssl->req_flags |= ISC_REQ_USE_SUPPLIED_CREDS;
      connssl->connecting_state = ssl_connect_2_writing;
      infof(data, "schannel: a client certificate has been requested\n");
      return CURLE_OK;
    }



Since I was not sure how caller will supply information about user selected cert I did not try above.

**Comment by jeroen** [comment]
OK I am on vacation now will look into this next week. It would really help if you can provide some mock server/cert for me to test.

**Comment by jeroen** [comment]
@bagder

**Comment by jeroen** [comment]
Actually can you open a new issue if enabling winssl is not sufficient

**Comment by ravisuhane** [comment]
ok done please check

**Comment by jeroen** [comment]
FYI: as of curl 3.0 we default to schannel on Windows 7 / 2008-R2 and up.
