### ISSUE TITLE
Getting Error in curl::curl_fetch_memory(url, handle = handle) : Timeout was reached

### ISSUE THREAD

**Issue by Scorpion07** [jeroen/curl#102]
Hi, I tried to scrape linkedin person data using the following command 
`in.auth <- inOAuth(app_name, consumer_key, consumer_secret)`  from the **Rlinkedin** library in R version 3,3,1 (2016-06-21) on windows 8.1 os. I am getting this error `Error in curl::curl_fetch_memory(url, handle = handle) : Timeout was reached`.

**Comment by jeroen** [comment]
Probably an issue with your internet connection. Otherwise you need to report this at `Rlinkedin`.
