### ISSUE TITLE
Regression for empty forms

### ISSUE THREAD

**Issue by jeroen** [jeroen/curl#103]
This unit test in httr now freezes: 

```r
library(httr)
POST("http://httpbin.org/post", body = list(), encode = "multipart")
```

Likely caused by https://github.com/jeroen/curl/commit/1e7ec7769ffdba7cbac3b5e2540c0e5ee72a21c2.

**Comment by kongdd** [comment]
When post empty parameters, some error encoded characters occur:

`library(httr)
x <- list(
  a = "",
  b = ""
)
p <- POST(
  "http://httpbin.org/post",
  body = x,
  verbose(),
  encode = "multipart"
) %>% content()

str(p$form)`

In the console, echo:
`-> POST /post HTTP/1.1
-> Host: httpbin.org
-> User-Agent: libcurl/7.53.1 r-curl/2.7 httr/1.2.1
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> Content-Length: 234
-> Expect: 100-continue
-> Content-Type: multipart/form-data; boundary=------------------------63a63d36d5e2ab59
-> 
>> --------------------------63a63d36d5e2ab59
>> Content-Disposition: form-data; name="a"
>> 
>> x梥
>> 
>> --------------------------63a63d36d5e2ab59
>> Content-Disposition: form-data; name="b"
>> 
>> @7S	
>> --------------------------63a63d36d5e2ab59--

<- HTTP/1.1 100 Continue
<- HTTP/1.1 200 OK
<- Connection: keep-alive
<- Server: meinheld/0.6.1
<- Date: Mon, 03 Jul 2017 14:43:56 GMT
<- Content-Type: application/json
<- Access-Control-Allow-Origin: *
<- Access-Control-Allow-Credentials: true
<- X-Powered-By: Flask
<- X-Processed-Time: 0.00165581703186
<- Content-Length: 590
<- Via: 1.1 vegur
<- 

str(p$form)
List of 2
 $ a: chr "x<U+FFFD>s\n"
 $ b: chr "@7S\t"
`

**Comment by jeroen** [comment]
Thanks! Great catch. FYI the bug was this [section](https://curl.haxx.se/libcurl/c/curl_formadd.html) from the libcurl manual:

> **CURLFORM_CONTENTSLENGTH**
>
> followed by a long giving the length of the contents. If you pass a 0 (zero) for this option, libcurl will instead do a strlen() on the contents to figure out the size. If you really want to send a zero byte content then you must make sure strlen() on the data pointer returns zero.
