### ISSUE TITLE
SEC_E_UNSUPPORTED_FUNCTION / libcurl error#35

### ISSUE THREAD

**Issue by mpadge** [jeroen/curl#105]
The CRAN win-builder `r-dev` machine generates two errors on my [`bikedata`](https://github.com/mpadge/bikedata) package - in both cases only on `r-dev`, but nowhere else (including appveyor):
```
Found the following (possibly) invalid URLs:
  URL: https://tfl.gov.uk/modes/cycling/santander-cycles
    From: inst/doc/bikedata.html
    Status: Error
    Message: libcurl error code 35:
    	error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```
and then via the same URL
```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_UNSUPPORTED_FUNCTION (0x80090302) - Die angeforderte Funktion wird nicht unterstützt.
Calls: store_bikedata ... request_fetch -> request_fetch.write_memory -> <Anonymous> -> .Call
```
("Die angeforderte Funktion wird nicht unterstützt" = "The requested function is not supported")

If you're quick the win-builder log is [here](https://win-builder.r-project.org/FIgcWOCr8zcJ/00check.log)

**Comment by jeroen** [comment]
Can you check if this is fixed now?

**Comment by mpadge** [comment]
Yep, all good. Thanks for the quick changes!
