### ISSUE TITLE
about uploading to FTP with curl

### ISSUE THREAD

**Issue by cderv** [jeroen/curl#106]
I was wondering if it is possible to upload a file to a FTP via `curl` package. 

It is possible with `curl` with something like `curl -T koc_dance.mp3 ftp://myftpsite.com/mp3/ --user myname:mypassword`

With `libcurl` and its `curl_easy_setopt`, it is also possible. 

I manage to do it for a text file creating a handle like this : 
```r
filetoupload <- file("file_to_upload.txt", "rb")

h <- new_handle() %>%
  handle_setopt(userpwd = "user:pwd", upload = 1L, readfunction = function(size) {
    readBin(filetoupload, raw(), size)
  })
```

However, after I am not sure wich function to use. I manage to upload the file with 

```r
con <- curl_fetch_memory("sftp://example/path/to/file_to_upload.txt", handle = h)
```
 and checking that `con$status_code == 0` but the return value form `curl_fetch_memory` is not so helpful. (no progress upload bar, or info that upload is 100%)

Should I use `curl` package like this ? Is there another solution ? 
Should this package include a `curl_upload` for ftp as it has a `curl_download` ? 
What is your opinion on this use case ?

Thanks

**Comment by jeroen** [comment]
Have a look at https://github.com/hadley/devtools/blob/master/R/upload-ftp.r

**Comment by cderv** [comment]
ok so it is hide in `devtools` for win-builder. It seems I got it right but spend some time on it whereas it already exists. thanks for the link.
Why not include such a function in `curl` directly ?

**Comment by jeroen** [comment]
Yes youre right ill move this into curl. But its so simple you can just copy the code you need.

**Comment by cderv** [comment]
Yes I will do that. 
But it is not so easy to come with this code when you're not a curl expert. Seems simple now that I understand more about handles and curl options. It was a good learning experience to come with code. 
Maybe it could just be added as an example of usage for curl using handles and not included as a helper function.

**Comment by shrektan** [comment]
@jeroen Thanks for pointing out the code to upload to FTP. However, I find it's about 4~5 times slower than using a FTP software like [Core FTP LE](http://www.coreftp.com/) when uploading a large file.

It's tested in an internal network so I'm pretty sure it's not due to the traffic jam of the network...

Would you mind enlighten me the possible reason why using R's curl function is much slower? Is there any way to speed it up?
