### ISSUE TITLE
HTTP 1.0 Redirect errors using curl connection, but not passing url directly to readLines or file

### ISSUE THREAD

**Issue by misea** [jeroen/curl#107]
I am connecting to a website that returns a 301 redirect status over HTTP 1.0 . I can read the data by passing the URL directly to readLines, but receive an error using readLines on a connection created with curl()

I found issues both using curl 2.7 and the current dev version 2.8.9000, though the issues were different. Command line curl -L works fine.

```r
# The following works, and I believe wrapping URL with file() connection does as well
readLines('https://digital.library.unt.edu/ark:/67531/metadc29275/m1/129')

# But this produces errors on both 2.7 (Error in read_connection_(x,n)) 
# and 2.8.9000 (SSLRead() return error -9806)
readLines(curl::curl('https://digital.library.unt.edu/ark:/67531/metadc29275/m1/129'))

# Redirects do work for some servers - perhaps due to HTTP 1.1 keep alive
readLines(curl::curl('http://httpbin.org/redirect-to?url=http://httpbin.org/html?status_code=301'))

# RCurl works if I pass followlocation=TRUE for the handle options
getURL('https://digital.library.unt.edu/ark:/67531/metadc29275/m1/129', .opts=c(followlocation=TRUE))
```
I am not sure whether there is something wrong with the server. Because server config may change, here are the headers it is currently returning

```
HTTP/1.0 301 MOVED PERMANENTLY
Date: Wed, 19 Jul 2017 20:55:54 GMT
Server: Apache/2.2.15 (Red Hat)
Content-Length: 0
Location: https://digital.library.unt.edu/ark%3A/67531/metadc29275/m1/129/
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
Connection: close
Content-Type: text/html; charset=utf-8
```
I originally found this error using xml2 and the related issue is https://github.com/r-lib/xml2/issues/182

**Comment by jeroen** [comment]
Can you please include your sessionInfo()

**Comment by jeroen** [comment]
Moving discussion to https://github.com/r-lib/xml2/issues/182 and https://github.com/curl/curl/issues/1691.

**Comment by misea** [comment]
Thank you. I will use the workaround, but I still have a nagging question. Why does explicitly setting followlocation=TRUE fix this problem? Does that silently change Accept headers or compression handling from the R wrapper library? Also not sure why the server would only throw for the Mac build, but I'll ask that question on the libcurl folks.
