### ISSUE TITLE
Extra file descriptors for polling

### ISSUE THREAD

**Issue by gaborcsardi** [jeroen/curl#109]
This is just an idea. It would be cool to be able to poll not just for the libcurl downloads, but other file descriptors as well. I could use this to poll for I/O from processes for example. `curl_multi_wait` supports this already, via the `extra_fds` and `extra_nfds` arguments. 

Unfortunately this will not work on the R connection level, since we cannot get the fds of the connections, but this might also be a good thing, considering the current half-supported status of custom connections.

But we could just pass in file descriptors in an integer vector.

**Comment by gaborcsardi** [comment]
Maybe an easier alternative is to provide a wrapper to `curl_multi_fdset`, and then I can just get the file descriptors and poll them myself. 

@jeroen So how about that?

**Comment by gaborcsardi** [comment]
I can also send a PR.

**Comment by jeroen** [comment]
I don't really understand the use case but perhaps a PR can help with that.

**Comment by gaborcsardi** [comment]
I just want to poll for output from curl http connections and processx
stdout/stderr pipes at the same time, with a single call.

**Comment by gaborcsardi** [comment]
So, if could poll with a single call, that would be awesome, because then I could create a single event loop for external processes and HTTP connections. I.e. (using pseudocode):

```r
tasks <- list(
  processx::process$new("some-long-running-process"),
  processx::process$new("another-process"),
  http::get("https://...")
  http::get("https://...")
  ...
)
while (length(tasks)) {
  update_statusbar(tasks)
  events <- poll(tasks, timeout = 100)
  tasks <- handle_events(tasks, events)  
}
```
