### ISSUE TITLE
version 2.8.1 breaks support for Windows XP

### ISSUE THREAD

**Issue by justa9** [jeroen/curl#112]
Hello.

It seems that curl version 2.8.1 breaks support for Windows XP.

The error reported (popup) is "The procedure entry point IdnToAscii could not be located in the dynamic link library KERNEL32.dll" and R states that it is "unable to load shared object" for the file under "...curl/libs/i386/curl.dll'

Thank you.

**Comment by jeroen** [comment]
Yes we added support for IDN which requires windows Vista and up. The [microsoft docs](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318149(v=vs.85).aspx) say: 

> Windows XP, Windows Server 2003: The required header file and DLL are part of the "Microsoft Internationalized Domain Name (IDN) Mitigation APIs" download, available at the MSDN Download Center.

However these download links are dead because MS has retired XP... maybe you can find them somewhere else?

**Comment by justa9** [comment]
Thank you for the reply. Unfortunately, I could not find the original setup file for this KB anywhere.

**Comment by jeroen** [comment]
Yes that's one problem of using an OS which has been deprecated for many years now.
