### ISSUE TITLE
curl argument -d

### ISSUE THREAD

**Issue by ghost** [jeroen/curl#115]
hi, 
I have a working command line curl command that uses the argument -d.
However I don't seem to be able to implement this in the R curl package, as data is not a viable options. I tried seekdata, and a couple of other, but I seem to fail in finding a solution.

any help?

this is the line I have now:
handle_setopt(h, 
.list=list( userpwd = "AAA:BBB!",
seekdata = '{"criteria": {"fieldName": "cntn_cf_id", "operator": "equals", "value": "XXXX"}}'))

**Comment by syntheso** [comment]
Did you resolve this?

**Comment by jeroen** [comment]
Can you try copypostfields, like here: https://cran.r-project.org/web/packages/curl/vignettes/intro.html#posting_forms
