### ISSUE TITLE
installing source package fails

### ISSUE THREAD

**Issue by piptoma** [jeroen/curl#117]
At my workplace, packages need to be installed from source, because R cannot directly access the internet. When installing the source version of curl, I get the following error message. Do you have an idea why the installation fails? I already have installed dozens of other packages with the same code.

    > install.packages("H:/R_3.4_packages/curl_2.8.1.tar.gz",
    +                  repos = NULL,
    +                  type = "source",
    +                  INSTALL_opts = "--no-test-load",
    +                  lib = "Z:/3.4.1")
    '\\my\path'
    CMD.EXE was started with the above path as the current directory.
    UNC paths are not supported.  Defaulting to Windows directory.
     * installing *source* package 'curl' ...
    ** package 'curl' successfully unpacked and MD5 sums checked
    ** libs
    Building curl with 'openssl' crypto backend.
    rm -f curl.dll callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o interrupt.o multi.o nslookup.o reflist.o split.o utils.o version.o winidn.o libwinhttp.dll.a winhttp.def
    "C:/PROGRA~1/R/R-32~1.0/bin/x64/Rscript.exe" --vanilla "../tools/winlibs.R"
    Warning messages:
    1: In download.file("https://github.com/rwinlib/libcurl/archive/v7.54.1.zip",  :
      downloaded length 4096 != reported length 4006112
    2: In unzip("lib.zip", exdir = "../windows") :
      error 1 in extracting from zip file
    echo '#include <curl/curl.h>' | gcc -m64 -E -I../windows/libcurl-7.54.1/include -DCURL_STATICLIB -std=gnu99 -xc - | grep "^[ \t]*CURLOPT_.*," | sed s/,// > ../tools/option_table.txt
    <stdin>:1:23: fatal error: curl/curl.h: No such file or directory
    compilation terminated.
    cp winhttp64.def.in winhttp.def
    dlltool --as as -m i386:x86-64 --as-flags --64 -k  --dllname winhttp.dll --input-def winhttp.def --output-lib libwinhttp.dll.a
    gcc -m64 -I"C:/PROGRA~1/R/R-32~1.0/include" -DNDEBUG -I../windows/libcurl-7.54.1/include -DCURL_STATICLIB    -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c callbacks.c -o callbacks.o
    In file included from callbacks.c:1:0:
    curl-common.h:2:23: fatal error: curl/curl.h: No such file or directory
    compilation terminated.
    make: *** [callbacks.o] Error 1
    Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-32~1.0/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-32~1.0/share/make/winshlib.mk" SHLIB="curl.dll" WIN=64 TCLBIN=64 OBJECTS="callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o interrupt.o multi.o nslookup.o reflist.o split.o utils.o version.o winidn.o"' had status 2
    ERROR: compilation failed for package 'curl'
    * removing 'Z:/3.4.1/curl'
    Warning in install.packages :
      running command '"C:/PROGRA~1/R/R-32~1.0/bin/x64/R" CMD INSTALL --no-test-load -l "Z:\3.4.1" "H:/R_3.4_packages/curl_2.8.1.tar.gz"' had status 1
    Warning in install.packages :
    installation of package ‘H:/R_3.4_packages/curl_2.8.1.tar.gz’ had non-zero exit status

**Comment by jeroen** [comment]
If you cannot access internet, you should download and install the [binary package for windows](https://cran.r-project.org/web/packages/curl/index.html) rather than the source pkg.

**Comment by piptoma** [comment]
Unfortunately, I cannot download the binary package (it gets blocked). I have to speak with the IT department...

**Comment by jeroen** [comment]
Well that's probably also the reason that the install above fails then.

**Comment by niguarino** [comment]
I am having a similar issue where I am having trouble installing curl and cannot connect to the internet. When I try to install curl, R tries to connect to a URL. I downloaded the binaries zip file locally, but I don't know how to get R to refer to the local file instead of the URL. Do you have any advice?

```
> install.packages("curl_4.3.tar.gz", repos = NULL, type = "source")
Installing package into ‘C:/Path/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'curl' ...
** package 'curl' successfully unpacked and MD5 sums checked
** using staged installation
** libs

*** arch - i386
rm -f curl.dll callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o interrupt.o multi.o nslookup.o reflist.o split.o ssl.o typechecking.o utils.o version.o winidn.o writer.o libwinhttp.dll.a winhttp.def
"C:/PROGRA~1/R/R-40~1.2/bin/i386/Rscript.exe" "../tools/winlibs.R" 7.64.1
Error in download.file(sprintf("https://github.com/rwinlib/libcurl/archive/v%s.zip",  :
  cannot open URL 'https://github.com/rwinlib/libcurl/archive/v7.64.1.zip'
In addition: Warning message:
In download.file(sprintf("https://github.com/rwinlib/libcurl/archive/v%s.zip",  :
  InternetOpenUrl failed: 'The server name or address could not be resolved'
Execution halted
make: *** [Makevars.win:14: winlibs] Error 1
ERROR: compilation failed for package 'curl'
* removing 'C:/Path/win-library/4.0/curl'
Warning in install.packages :
  installation of package ‘curl_4.3.tar.gz’ had non-zero exit status
```

**Comment by jeroen** [comment]
My advice is still: To install on Windows without internet connection you should download the [windows binaries](https://cran.r-project.org/web/packages/curl/index.html)  rather than the source pkg.

**Comment by niguarino** [comment]
After downloading the curl_4.3.zip file (the binaries), where should I save
it so that R doesn't try to access the URL but instead tries to access the
local .zip file? I am new to R, so if you could break it down for me, that
would be helpful. Even when I save curl_4.3.zip in my Documents folder, R
is still trying to access the URL, which is causing an error.

**Comment by niguarino** [comment]
I see now - I should install curl_4.3.zip in place of curl_4.3.tar.gz. That worked! Thank you!
