### ISSUE TITLE
Client certificate authentication using curl with schannel on Windows platform

### ISSUE THREAD

**Issue by ravisuhane** [jeroen/curl#119]
When certificate private key is stored on Windows certificate store / TPM (you can not export the private key), there is not way to supply the client certificate to curl schannel. 

code in schannel.c tries to continue without client cert and authetication fails on server which mandates client auth. 

```c
/* If the server has requested a client certificate, attempt to continue
the handshake without one. This will allow connections to servers which
request a client certificate but do not require it. */
if(sspi_status == SEC_I_INCOMPLETE_CREDENTIALS &&
!(connssl->req_flags & ISC_REQ_USE_SUPPLIED_CREDS)) {
connssl->req_flags |= ISC_REQ_USE_SUPPLIED_CREDS;
connssl->connecting_state = ssl_connect_2_writing;
infof(data, "schannel: a client certificate has been requested\n");
return CURLE_OK;
}
```
there should be a way to supply the windows certificate context to curl/schannel.

I tested latest curl code with schannel and TLS session does not use client certificate for auth and it fails.

Can you give me idea where can I add my custom method in curl which can supply windows certificate context to curl for schannel ?

**Comment by jeroen** [comment]
Are you using the winssl or openssl build of the curl package? I think you need the winssl version:

```r
Sys.setenv(LIBCURL_BUILD="winssl")
install.packages('curl', type = "source")
```

Can you tell me exactly what error you get? Make sure to set `verbose=TRUE` in the handle.

@bagder does curl support client certs?

**Comment by jeroen** [comment]
Did you try setting [`CURLOPT_SSLCERT`](https://curl.haxx.se/libcurl/c/CURLOPT_SSLCERT.html) ?

**Comment by ravisuhane** [comment]
I am using winssl and it uses schannel.c internally.  
The code block in schannle.c which I mentioned in my above post suppress the client cert request and proceed and client auth fail on server.


Please refer AcquireCredentialsHandle(...) in schannel.c which does not supply client certificate context.
Without this this code will not work.  There is no code which gets the certifcate context from Windows store and supply it to AcquireCredentialsHandle.

If I hardcode and supplied cert context in schannel.c AcquireCredentialsHandle(...)  then it works.

**Comment by jeroen** [comment]
So it sounds like you should be doing a pull request to [libcurl](https://github.com/curl/curl) to add support for this? How do you expect me to solve this in the R bindings?

**Comment by ravisuhane** [comment]
i am not sure about that , i did code changes for my testing. I am looking for a proper way to pass the info to curl for schannel.

**Comment by jeroen** [comment]
If the problem is in `schannel.c` I suggest you open an issue in the [libcurl repository](https://github.com/curl/curl). It looks like the current implementation does not query the cert store; it only checks for `CURLOPT_SSLCERT`. 

Once it is supported in libcurl we can take advantage of it in R.

**Comment by jeroen** [comment]
You're talking in the wrong repo. This repo only contains the R bindings. You need https://github.com/curl/curl

**Comment by ravisuhane** [comment]
Got it. I understand that and opened issue in main repo. 
Just wanted to know what is this "R bindings" why do you call it "R"?

Thanks for your time and reply.

**Comment by gvollant** [comment]
the pull request https://github.com/curl/curl/pull/4356 add support of client certificate in .P12 or .PFX file with compiling whith schannel

**Comment by jeroen** [comment]
Cool, thanks!
