### ISSUE TITLE
Logging verbose curl output

### ISSUE THREAD

**Issue by sebastian-c** [jeroen/curl#120]
I saw [this question](https://stackoverflow.com/q/46299318/1465387) on StackOverflow which attempts to get the verbose output when performing an FTP download and preserve it in R. `RCurl` [has a function](https://stackoverflow.com/q/19982087/1465387) to do something similar, but it doesn't seem to work for FTP. Is there anything in `curl` to support this?

**Comment by jeroen** [comment]
Try this:

```r
upload_ftp <- function(file, url, verbose = TRUE){
  log <- rawConnection(raw(), 'r+')
  on.exit(close(log))
  stopifnot(file.exists(file))
  stopifnot(is.character(url))
  con <- file(file, open = "rb")
  on.exit(close(con))
  h <- curl::new_handle(upload = TRUE, filetime = FALSE, debugfunction = function(type, data){
    writeBin(data, log)
  })
  curl::handle_setopt(h, readfunction = function(n){
    readBin(con, raw(), n = n)
  }, verbose = verbose)
  try({
    curl::curl_fetch_memory(url, handle = h)
  })
  rawToChar(rawConnectionValue(log))
}

```

**Comment by sebastian-c** [comment]
Thanks for your time, I didn't know you could set a debug function in the handle.

**Comment by s-fleck** [comment]
(original asker of stackoverflow question here)

Based on your answer, this does _nearly_ what I wanted:

```
curl_download_with_log <- function(
  url,
  destfile,
  verbose = TRUE
){
  log <- rawConnection(raw(), 'r+')
  on.exit(close(log))
  stopifnot(is.character(url))

  h <- curl::new_handle(
    debugfunction = function(type, data){
      writeBin(data, log)
    },
    verbose = verbose
  )

  try({
    curl::curl_download(url, destfile = destfile, handle = h)
  })

  rawToChar(rawConnectionValue(log))
}

```
log <- curl_download_with_log(
  url = inurl,
  destfile = outfile
)
``

The only issue is that the whole file I download is also included in the log. Is there a way to prevent this? I tried to work mysefl through the libcurl documentation, but i don't understand it well enough :/

**Comment by jeroen** [comment]
The `type` parameter in `debugfunction` contains a number (1 through 5) about if the `data` is content or log stuff. I think you can use that to filter out content data.

**Comment by s-fleck** [comment]
Works like a charm, thanks :)
