### ISSUE TITLE
no sftp support by default anymore

### ISSUE THREAD

**Issue by exhibit777** [jeroen/curl#125]
I use httr/curl packages to get files from sftp. It worked before updating R and all the packages to the latest versions. Somehow libssh_version is empty. How do I enable sftp support? It is on windows OS.

GET(sftp://10.10.10.10:10/somedir/, authenticate("user", "my_pass"))
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Protocol "sftp" not supported or disabled in libcurl

curl_version()
$version
[1] "7.56.0"

$ssl_version
[1] "(OpenSSL/1.1.0f) WinSSL"

$libz_version
[1] "1.2.8"

$libssh_version
[1] NA

$libidn_version
[1] NA

$host
[1] "x86_64-w64-mingw32"

$protocols
 [1] "dict"   "file"   "ftp"    "ftps"   "gopher" "http"   "https"  "imap"   "imaps"  "ldap"   "ldaps"  "pop3"   "pop3s"  "rtsp"   "smtp"  
[16] "smtps"  "telnet" "tftp"  

$ipv6
[1] TRUE

$http2
[1] FALSE

$idn
[1] TRUE

**Comment by jeroen** [comment]
Yes I dropped ssh support indeed. I thought nobody was using it. I suppose I can restore it for the next release if you'd like that.

**Comment by exhibit777** [comment]
I would be glad to have it back, thanks! As a workaround now I use RCurl:getBinaryURL

**Comment by tscheypidi** [comment]
Our group is using ssh support as well (scp). We would be very glad if you could reintegrate it!

Just a question in that context: For our windows users downgrading to curl 2.8.1 solved the problem. However, under Linux a downgrade did not fix it. Could you give me a hint, how a workaround under Linux could look like?

**Comment by jeroen** [comment]
That's the thing, on MacOS / Linux, the system detemines how libcurl is configured. So we can't control that

Perhaps we should make a separate scp package instead of using curl for this? What exactly is it you need to do? Just download a file?

**Comment by tscheypidi** [comment]
We use it for downloading files from a server which requires SSH key authentication. I like having all the different protocols provided by one package, but if a separate package would simplify the whole process that would work for us as well. How could a development of a separate package help in this context?

**Comment by tscheypidi** [comment]
Fantastic, thanks a lot!

**Comment by jeroen** [comment]
Can you please test the [dev version](https://github.com/jeroen/curl#devel-version)?

**Comment by exhibit777** [comment]
I have tested the dev version and sftp protocol works again as expected. Thanks!!

**Comment by tscheypidi** [comment]
I tested it now as well. scp works again in Windows, thanks!

**Comment by jeroen** [comment]
This has landed on CRAN in curl 3.1.
