### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle) :    SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by mhnierhoff** [jeroen/curl#128]
Hi,
thanks for your awesome work so far. 

It seems, that I have a problem since the package update - However, I am not 100% sure whether this error message is more related to the API or the tool of the service provider.
`> current_Connection_status <- wt.connection.test()
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL certificate problem: certificate has expired
Called from: curl::curl_fetch_memory(url, handle = handle)`

Setup:
On our Shiny server in our intranet runs cronjob every night a script which queries the data from a tool provider via API. This worked for many months without problems. But since Friday it stopped working.
I am unclear how I interpret this error message and how I solve the problem? On the Shiny server runs CentOS and I work locally with Windows.

Thanks in advance.

**Comment by jeroen** [comment]
Does your shiny server have a valid https certificate? Does it have a green lock when you open the same server in the browser?

**Comment by mhnierhoff** [comment]
Hi Jeroen,

Thanks for your reply. The shiny server setup is just standard without https, because the server is located in the intranet. However, the whole thing does not work on my Windows computer as well. I got the posted error message locally.

Thanks in advance.

**Comment by jeroen** [comment]
But does the tool provider API work over https? The error means there is a problem with an https cert somewhere.

**Comment by mhnierhoff** [comment]
Hi Jeroen,

thanks for your help. At least the problem was on side of the tool provider API and seems to be fixed now.
