### ISSUE TITLE
Unable to create new handle

### ISSUE THREAD

**Issue by cpsievert** [jeroen/curl#129]
```shell
curl --version
curl 7.36.0 (x86_64-unknown-linux-gnu) libcurl/7.36.0 zlib/1.2.8
Protocols: dict file ftp gopher http imap pop3 rtsp smtp telnet tftp 
Features: IPv6 Largefile libz 
```

```r
curl::new_handle()
# Error in curl::new_handle() : An unknown option was passed in to libcurl
```

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value
#>  version  R version 3.4.2 (2017-09-28)
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  tz       America/New_York
#>  date     2017-10-26
#> Packages -----------------------------------------------------------------
#>  package   * version date       source
#>  backports   1.0.5   2017-01-18 CRAN (R 3.3.2)
#>  base      * 3.4.2   2017-09-29 local
#>  compiler    3.4.2   2017-09-29 local
#>  datasets  * 3.4.2   2017-09-29 local
#>  devtools    1.13.3  2017-08-02 CRAN (R 3.4.2)
#>  digest      0.6.12  2017-01-27 CRAN (R 3.3.2)
#>  evaluate    0.10.1  2017-06-24 cran (@0.10.1)
#>  formatR     1.4     2016-05-09 CRAN (R 3.2.4)
#>  graphics  * 3.4.2   2017-09-29 local
#>  grDevices * 3.4.2   2017-09-29 local
#>  htmltools   0.3.6   2017-04-28 cran (@0.3.6)
#>  knitr       1.17    2017-08-10 cran (@1.17)
#>  magrittr    1.5     2014-11-22 CRAN (R 3.1.1)
#>  memoise     1.1.0   2017-04-21 cran (@1.1.0)
#>  methods   * 3.4.2   2017-09-29 local
#>  Rcpp        0.12.13 2017-09-28 cran (@0.12.13)
#>  rmarkdown   1.6     2017-06-15 cran (@1.6)
#>  rprojroot   1.2     2017-01-16 CRAN (R 3.3.2)
#>  stats     * 3.4.2   2017-09-29 local
#>  stringi     1.1.5   2017-04-07 cran (@1.1.5)
#>  stringr     1.2.0   2017-02-18 CRAN (R 3.3.2)
#>  tools       3.4.2   2017-09-29 local
#>  utils     * 3.4.2   2017-09-29 local
#>  withr       2.0.0   2017-10-26 Github (jimhester/withr@a43df66)
#>  yaml        2.1.14  2016-11-12 cran (@2.1.14)
```

**Comment by jeroen** [comment]
Can you `traceback()` where this happens?

**Comment by jeroen** [comment]
Do you have multiple copies of `libcurl` installed on the machine? This stuff typically can only happen if you compile against a more recent version of libcurl but then load an old version at runtime.

**Comment by cpsievert** [comment]
```r
traceback()
#> 2: .Call(R_new_handle)
#> 1: curl::new_handle()
```

```shell
$ apt list --installed | grep 'libcurl'

libcurl3/trusty-updates,trusty-security,now 7.35.0-1ubuntu2.12 amd64 [installed]
libcurl3-gnutls/trusty-updates,trusty-security,now 7.35.0-1ubuntu2.12 amd64 [installed]
libcurl4-openssl-dev/trusty-updates,trusty-security,now 7.35.0-1ubuntu2.12 amd64 [installed]
```

> compile against a more recent version of libcurl but then load an old version at runtime.

I'm pretty sure I'm compiling against a recent version:

```shell
$ ls /usr/local/lib
libcurl.a   libcurl.so    libcurl.so.4.3.0  libudunits2.la  libudunits2.so.0      opencpu    python2.7  R
libcurl.la  libcurl.so.4  libudunits2.a     libudunits2.so  libudunits2.so.0.1.0  pkgconfig  python3.4  site_ruby
```

Any idea how I can check the runtime version?

**Comment by jeroen** [comment]
It's probably loading `/usr/lib/libcurl.so` at runtime instead of the one in `/usr/local/lib`. Try:

```
ldd /usr/local/lib/R/site-library/curl/libs/curl.so
```

**Comment by cpsievert** [comment]
Thanks! Removing the local build and reinstalling with `apt` seems to have fixed the problem 🍻 

```shell
$ sudo apt-get remove libcurl4-openssl-dev
$ sudo apt-get install -y libcurl4-openssl-dev
```

```r
install.packages("curl")
```

**Comment by maytest** [comment]
I tried all of these suggestions, unfortunately I'm getting errors when trying to install specific package versions with github 
![pasted graphic 1](https://user-images.githubusercontent.com/38874596/43592342-f551522e-963a-11e8-800e-533229e29547.png)
![pasted graphic 2](https://user-images.githubusercontent.com/38874596/43592352-f846e278-963a-11e8-89a9-d026a7b8c457.png)
![pasted graphic3](https://user-images.githubusercontent.com/38874596/43592355-fa387222-963a-11e8-8a29-d9971ccb42de.png)

 Can Anyone help me fix the problem? Thanks!

**Comment by alexmosc** [comment]
Hello,

I faced the same error after making some updates on a centos machine.

We tried updating the necessary system libraries, and I checked several R `curl `versions, all failed.

After reading this topic I run the following commands.

`sudo yum list installed | grep 'libcurl'
libcurl.x86_64                     7.29.0-51.el7_6.3                   installed
libcurl-devel.x86_64               7.29.0-51.el7_6.3                   installed
`

` sudo yum list installed | grep 'curl'
curl.x86_64                        7.29.0-51.el7_6.3                   installed`

` which curl
/usr/bin/curl
`
`which libcurl
/usr/bin/which: no libcurl in (/usr/lib64/libcurl.so.4.3.0:/usr/lib64/libcurl.so.4:/usr/lib64/libcurl.so:/usr/local/lib64/R/lib/libR.so: etc....`

`ldd /home/me/R/x86_64-pc-linux-gnu-library/3.6/curl/libs/curl.so
        linux-vdso.so.1 =>  (0x00007ffea11e2000)
        libcurl.so.4 => /lib64/libcurl.so.4 (0x00007f0c37a04000)
        libR.so => not found
        libc.so.6 => /lib64/libc.so.6 (0x00007f0c37637000)
        libidn.so.11 => /lib64/libidn.so.11 (0x00007f0c37404000)
        libssh2.so.1 => /lib64/libssh2.so.1 (0x00007f0c371d7000)
        libssl3.so => /lib64/libssl3.so (0x00007f0c36f85000)
        libsmime3.so => /lib64/libsmime3.so (0x00007f0c36d5e000)
        libnss3.so => /lib64/libnss3.so (0x00007f0c36a31000)
        libnssutil3.so => /lib64/libnssutil3.so (0x00007f0c36802000)
        libplds4.so => /lib64/libplds4.so (0x00007f0c365fe000)
        libplc4.so => /lib64/libplc4.so (0x00007f0c363f9000)
        libnspr4.so => /lib64/libnspr4.so (0x00007f0c361bb000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0c35f9f000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f0c35d9b000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f0c35b4e000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f0c35865000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f0c35632000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f0c3542e000)
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f0c3521f000)
        libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007f0c34fca000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f0c34db4000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0c37e7b000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007f0c34b42000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f0c346df000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f0c344d7000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f0c342c7000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f0c340c3000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f0c33eaa000)
        libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f0c33c8d000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f0c33a66000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f0c3382f000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f0c335cd000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007f0c333ca000)`

R info.

`<html>
<body>


> capabilities('libcurl') libcurl     
TRUE  >  

> library(curl) Using libcurl 7.29.0 with NSS/3.36 

> sessionInfo() R version 3.6.0 (2019-04-26) Platform: x86_64-pc-linux-gnu (64-bit) Running under: CentOS Linux 7 (Core)  Matrix products: default BLAS:   /usr/local/lib64/R/lib/libRblas.so LAPACK: /usr/local/lib64/R/lib/libRlapack.so  locale:  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8      [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                   [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C         attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] **curl_5.0.0**  loaded via a namespace (and not attached): [1] compiler_3.6.0 tools_3.6.0    packrat_0.5.0
--
 
> | >
>


</body>
</html>`

OS info

`]$ hostnamectl
   Static hostname: infocore-backend02
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 6485a659878944ea8087794fc392476b
           Boot ID: be692957ce1442c68b07580025064575
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-957.1.3.el7.x86_64
      Architecture: x86-64
`

**Comment by jeroen** [comment]
@alexmosc can you show the complete output of `install.packages("curl")` process? I suspect you have a broken copy of another libcurl lingering on your machine.

**Comment by alexmosc** [comment]
Yes, I will do now. Thank you!

` install.packages("curl")
Installing package into ‘/home/burnakov_a/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/curl_5.0.0.tar.gz'
Content type 'application/x-gzip' length 682047 bytes (666 KB)
==================================================
downloaded 666 KB

* installing *source* package ‘curl’ ...
** package ‘curl’ successfully unpacked and MD5 sums checked
** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS= 
Using PKG_LIBS=-lcurl  
** libs
rm -f curl.so callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o interrupt.o multi.o nslookup.o options.o reflist.o split.o ssl.o typechecking.o utils.o version.o winidn.o writer.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c callbacks.c -o callbacks.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c curl.c -o curl.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c download.c -o download.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c escape.c -o escape.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c fetch.c -o fetch.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c form.c -o form.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c getdate.c -o getdate.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c handle.c -o handle.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c ieproxy.c -o ieproxy.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c init.c -o init.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c interrupt.c -o interrupt.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c multi.c -o multi.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c nslookup.c -o nslookup.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c options.c -o options.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c reflist.c -o reflist.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c split.c -o split.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c ssl.c -o ssl.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c typechecking.c -o typechecking.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c utils.c -o utils.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c version.c -o version.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c winidn.c -o winidn.o
gcc -std=gnu99 -I"/usr/local/lib64/R/include" -DNDEBUG -DSTRICT_R_HEADERS  -I/usr/local/include -fvisibility=hidden -fpic  -g -O2  -c writer.c -o writer.o
gcc -std=gnu99 -shared -L/usr/local/lib64/R/lib -L/usr/local/lib64 -o curl.so callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o interrupt.o multi.o nslookup.o options.o reflist.o split.o ssl.o typechecking.o utils.o version.o winidn.o writer.o -lcurl -L/usr/local/lib64/R/lib -lR
installing to /home/burnakov_a/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-curl/00new/curl/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (curl)

The downloaded source packages are in
	‘/tmp/RtmpsVXGYI/downloaded_packages’`

By the way, I somehow managed to create missing cymbolic links in `ldd` to get this:

![image](https://user-images.githubusercontent.com/12047099/224322807-06ab6c41-e073-464c-9504-7b175401af0d.png)

**Comment by alexmosc** [comment]
> 

I did find a curl instance there:

`(env) [burnakov_a@infocore-backend02 curl-7.65.3]$ ls /usr/local/include/curl
curlbuild.h  curl.h  curlrules.h  curlver.h  easy.h  mprintf.h  multi.h  stdcheaders.h  typecheck-gcc.h`

**Comment by alexmosc** [comment]
> If so, can you try this: https://github.com/jeroen/curl/issues/155#issuecomment-396697977

The only version should be in /usr/include/curl/curl.h


Yes! It works after removing the `...local/include/` version of `curl `and resinstalling R `curl`.

Many thanks!!!! I have almost started rolling back the backup on the machine, Phew!
