### ISSUE TITLE
Install on Alpine Linux

### ISSUE THREAD

**Issue by kenahoo** [jeroen/curl#136]
I'm experimenting with Alpine Linux because it's very stripped-down and produces very small Docker images for continuous-build systems.

When trying to install the `curl` package, it can't successfully find `libcurl`:

```
Using PKG_CFLAGS=
Using PKG_LIBS=-lcurl 
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libcurl was not found. Try installing:
 * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 * rpm: libcurl-devel (Fedora, CentOS, RHEL)
 * csw: libcurl_dev (Solaris)
If libcurl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libcurl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
```

There is a `libcurl` on the system, which I installed via `apk add curl-dev`, which gets me the following:

```
/ # apk info -R curl-dev
curl-dev-7.57.0-r0 depends on:
libcurl=7.57.0-r0
pkgconfig

/ # apk info -L curl-dev
curl-dev-7.57.0-r0 contains:
usr/bin/curl-config
usr/lib/libcurl.so
usr/lib/libcurl.a
usr/lib/pkgconfig/libcurl.pc
usr/share/aclocal/libcurl.m4
usr/include/curl/stdcheaders.h
usr/include/curl/curl.h
usr/include/curl/multi.h
usr/include/curl/mprintf.h
usr/include/curl/typecheck-gcc.h
usr/include/curl/system.h
usr/include/curl/easy.h
usr/include/curl/curlver.h

/ # apk info -L libcurl
libcurl-7.57.0-r0 contains:
usr/lib/libcurl.so.4
usr/lib/libcurl.so.4.5.0
```

It does seem to be found successfully by `pkg-config`:

```
/ # pkg-config --libs libcurl
-lcurl 
```

What else needs to be in place in order for the system library to be found?

**Comment by kenahoo** [comment]
A couple other facts:

* If I go into the `configure` script and tell it to print out the compiler command it's trying to run, and also don't hide the error output, I can see that it's not finding R:

```
# diff -u curl/configure curl-mine/configure
--- curl/configure
+++ curl-mine/configure
@@ -44,7 +46,8 @@
 echo "Using PKG_LIBS=$PKG_LIBS"
 
 # Test configuration
-echo "#include $PKG_TEST_HEADER" | ${CC} ${CPPFLAGS} ${PKG_CFLAGS} ${CFLAGS} -E -xc - >/dev/null 2>&1 || R_CONFIG_ERROR=1;
+echo "COMPILE: ${CC} ${CPPFLAGS} ${PKG_CFLAGS} ${CFLAGS} -E -xc -";
+echo "#include $PKG_TEST_HEADER" | ${CC} ${CPPFLAGS} ${PKG_CFLAGS} ${CFLAGS} -E -xc - || R_CONFIG_ERROR=1;
 
 # Customize the error
 if [ $R_CONFIG_ERROR ]; then
```

```
# ./configure
Found pkg-config cflags and libs!
./configure: line 40: /bin/R: not found
./configure: line 41: /bin/R: not found
./configure: line 42: /bin/R: not found
Using PKG_CFLAGS=
Using PKG_LIBS=-lcurl 
COMPILE:     -E -xc -
```

* Setting `R_HOME` as an environment variable gets a little farther, but not far enough:

```
# R_HOME=/usr ./configure
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-lcurl 
COMPILE: WARNING: ignoring environment value of R_HOME
gcc WARNING: ignoring environment value of R_HOME
-Os -fomit-frame-pointer  WARNING: ignoring environment value of R_HOME
-Os -fomit-frame-pointer -E -xc -
./configure: line 50: WARNING:: not found
```

* I manually set `R_HOME=/usr` inside the `configure` file, and now the compiler command launches successfully but hits a snag trying to find the system types:

```
# ./configure
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-lcurl 
COMPILE: gcc -Os -fomit-frame-pointer  -Os -fomit-frame-pointer -E -xc -
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "<stdin>"
# 1 "/usr/include/curl/curl.h" 1 3 4
# 37 "/usr/include/curl/curl.h" 3 4
# 1 "/usr/include/curl/curlver.h" 1 3 4
# 38 "/usr/include/curl/curl.h" 2 3 4
# 1 "/usr/include/curl/system.h" 1 3 4
In file included from /usr/include/curl/curl.h:38:0,
                 from <stdin>:1:
/usr/include/curl/system.h:397:25: fatal error: sys/types.h: No such file or directory
 #  include <sys/types.h>
                         ^
compilation terminated.
```

I'm guessing this is a problem with the `curl-dev` system package?  I couldn't figure out through the Googleverse where (the equivalent of?) `sys/types.h` is supposed to come from, though.

**Comment by jeroen** [comment]
Can you show me the output of this script?

```
PKG_TEST_HEADER="<curl/curl.h>"
PKG_CONFIG_NAME="libcurl"

R_HOME=`R RHOME`
PKGCONFIG_CFLAGS=`pkg-config --cflags ${PKG_CONFIG_NAME}`
CC=`${R_HOME}/bin/R CMD config CC`
CFLAGS=`${R_HOME}/bin/R CMD config CFLAGS`
CPPFLAGS=`${R_HOME}/bin/R CMD config CPPFLAGS`

echo "#include $PKG_TEST_HEADER" | ${CC} ${CPPFLAGS} ${PKG_CFLAGS} ${CFLAGS} -E -xc - >/dev/null
```

**Comment by kenahoo** [comment]
Here you go:

```
# sh test.sh
In file included from /usr/include/curl/curl.h:38:0,
                 from <stdin>:1:
/usr/include/curl/system.h:397:25: fatal error: sys/types.h: No such file or directory
 #  include <sys/types.h>
                         ^
compilation terminated.
```

**Comment by kenahoo** [comment]
I guess the `ignoring environment value of R_HOME` stuff was a goose chase, I should have been setting it to `/usr/lib/R` instead of `/usr`:

```
# R_HOME=`R RHOME` ./configure 
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-lcurl 
COMPILE: gcc -Os -fomit-frame-pointer  -Os -fomit-frame-pointer -E -xc -
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "<stdin>"
# 1 "/usr/include/curl/curl.h" 1 3 4
# 37 "/usr/include/curl/curl.h" 3 4
# 1 "/usr/include/curl/curlver.h" 1 3 4
# 38 "/usr/include/curl/curl.h" 2 3 4
# 1 "/usr/include/curl/system.h" 1 3 4
In file included from /usr/include/curl/curl.h:38:0,
                 from <stdin>:1:
/usr/include/curl/system.h:397:25: fatal error: sys/types.h: No such file or directory
 #  include <sys/types.h>
                         ^
compilation terminated.
```

Why this isn't being set from `R CMD INSTALL` is still a mystery, also why `sys/types.h` isn't found.

**Comment by jeroen** [comment]
Can you try installing `musl-dev`?

`R CMD INSTALL` is fine, the `R_HOME` variable gets set by R when it invokes `./configure` but I guess you were invoking configure manually to debug.

**Comment by kenahoo** [comment]
That does the trick!  Thanks.

You're right, when I was on my goose-chase with `R_HOME` I must have misinterpreted the messages coming from the `/usr/bin/R` script as meaning `R CMD INSTALL` somehow wasn't propagating `R_HOME`.

Would you agree that the `curl-dev` people should probably add `musl-dev` as a dependency?

**Comment by jeroen** [comment]
> Would you agree that the curl-dev people should probably add musl-dev as a dependency?

Yes exactly I was going to suggest you report this bug to the `curl-dev` maintainer.

**Comment by kenahoo** [comment]
Done: https://bugs.alpinelinux.org/issues/8343

**Comment by kenahoo** [comment]
One small thing you might be able to do in `curl` - if sensing `libcurl` fails, would it be possible to print out the error message from the compiler?  That would help redirect the user to the correct culprit.  Could capture the output with backticks & check the status message in `$?` or something.

**Comment by jeroen** [comment]
Maybe, it's just hard to extract the actual error message from all the output. In 98% of the cases the error happens because libcurl is not installed, hence you see the user friendly error message rather than a cryptic message about headers.
