### ISSUE TITLE
Error extracting data from NOAA ERDDAP, xtractomatic package

### ISSUE THREAD

**Issue by edu0702** [jeroen/curl#137]
I'am trying to match environmental data from the page of NOAA ERDDAP to my data base. Then I have latitude, longitude and date data and I want to extract the chlA and SST for those points. I'm using the following code.

`xpos <- targetCounts$LongitudeDD`
`ypos <- targetCounts$LatitudeDD`
`tpos <- targetCounts$Fecha.Inicio`

`SST2 <- xtracto(xpos, ypos, tpos, "erdMBsstd1day", xlen= .1, ylen= .1, verbose = TRUE)`

But I get this.

`Error in curl::curl_fetch_disk(url, x$path, handle = handle) : `
`  Timeout was reached: Connection timed out after 10000 milliseconds`

I have read some solutions in different phoros but nothing seems to help, I've even tried to change the DNS of google. I know this is not a problem of match because whit other ID used from ERDDAP which doesn't match I get this.

`[1] "tpos  (time) has elements out of range of the dataset"`
`[1] "time range in tpos"`
`[1] "2015-04-29,2017-10-25"`
`[1] "time range in ERDDAP data"`
`[1] "2010-06-09,2017-09-13"`
`Error in xtracto(xpos, ypos, tpos, "jplG1SST", xlen = 0.1, ylen = 0.1,  : `
`  Coordinates out of dataset bounds - see messages above`

I hope you could help me, please.

**Comment by sloredo214** [comment]
I have the same issue. I thought it was my internet connection but I have hardwired it now and still get the same error. I wonder if it a matter of the file being too big? I tried downloading the same dataset using the rerddapXtracto but I also had issues. @edu0702 , did you figure out what the problem was?

**Comment by jeroen** [comment]
This usually indicates your server is down. It is not a bug in the curl package.

**Comment by edu0702** [comment]
@sloredo214 I still don't know what was the problem.
@jeroen How can I know if it's really the server? And, do you know how to fix it, please?
