### ISSUE TITLE
R 3.1.x does not have `trimws`

### ISSUE THREAD

**Issue by gaborcsardi** [jeroen/curl#138]
So, either you need to depend on at least `3.2.0`, or (highly preferable for me) provide an alternative `trimws` implementation in `curl` itself. Something like:

```r
trimws <- function(x) {
  sub("\\s$", "", sub("^\\s+", "", x))
}
```

would do for `curl` I think. It is actually better than the base R implementation, because it handles all whitespace characters. Do you want this as a PR?

**Comment by jennybc** [comment]
Strong support from me re: a solution that supports R >= 3.1.

**Comment by jeroen** [comment]
What is broken exactly in 3.1?

**Comment by jennybc** [comment]
I use `curl::parse_headers_list()` in usethis and it calls `trimws()`, so I couldn't pass R CMD check on R 3.1.

**Comment by jeroen** [comment]
Does it work now in master?

**Comment by jennybc** [comment]
Yes! I can un-skip the test and, with curl in Remotes, all is well:

https://github.com/r-lib/usethis/commit/eb716fa93374395e2ca51f2d34437706062fcb82
