### ISSUE TITLE
Latest tag is missing

### ISSUE THREAD

**Issue by QuLogic** [jeroen/curl#143]
The latest tag here is 3.0, but 3.1 is the latest version on CRAN.

**Comment by jeroen** [comment]
OK I've added it.

**Comment by QuLogic** [comment]
Thanks!

**Comment by jeroen** [comment]
Np! Ps: would it be possible to provide r packages 'magick' and `pdftools' in fedora?

**Comment by QuLogic** [comment]
I packaged pdftools, but magick has a lot more Suggests to do.

**Comment by jeroen** [comment]
Cool thanks! You don't need all suggest! Most of those are just for running tests or documentation. Only the Imports are required.
