### ISSUE TITLE
Switch to weak references

### ISSUE THREAD

**Issue by jeroen** [jeroen/curl#151]
Currently the multi pool maintains a linked list of all handles, in order to protect them from the garbage collector. This code is a little ugly (though it seems to work).

Alternatively `multi_add()` could create a [weak reference](http://homepage.divms.uiowa.edu/~luke/R/references/weakfinex.html) from a pool to the handle. As I understand it, the weak reference object itself is automatically protected as long as the pool is reachable. We can trigger `multi_release()` in the weakref finalizer so that the handle becomes available again.

When the request completes or is canceled, the handle is removed from the pool, and the weakref has to be killed. I am not sure how this is done. Perhaps we just need to call `R_RunWeakRefFinalizer()` on the weakref object.

**Comment by gaborcsardi** [comment]
FWIW, igraph uses weak references, so there are some examples there: https://github.com/igraph/rigraph/blob/82fb65c273db5596966b4ae5dbe80e30a641b69a/tools/stimulus/rinterface_extra.c#L236-L251

**Comment by jeroen** [comment]
I couldn't find a helpful example in igraph. Do you know if what I said above is correct? It is unclear to me if we need to protect the weakref SEXP itself. Because if so, that just moves my problem from protecting handles to protecting weakref SEXPs.

Also I can't find documentation on how to undo the weakref.

**Comment by jeroen** [comment]
I've read that page a few times but I don't get it. 

I need a solution to prevent the GC from cleaning libcurl easy handles when the externalptr is no longer reachable but the handle is actually in use because it was added to a multi pool.

Luke has suggested to use a weak reference, but I don't understand how. If I create a weak reference with the pool as the key, and the handle as the value, this prevents the handle from being collected while the pool is reachable. But now I have the same problem because I need to somehow protect the weakref SEXP instead of the handle SEXP?
