### ISSUE TITLE
Use typed conditions

### ISSUE THREAD

**Issue by hadley** [jeroen/curl#154]
And think about whether some types of failure (e.g. failed connection) could provide a restart that would retry the request.

**Comment by hadley** [comment]
I still think this would be useful 😄

**Comment by jeroen** [comment]
How would you use this? E.g. if the condition is one of these error codes: https://curl.se/libcurl/c/libcurl-errors.html would that be informative at all?

**Comment by hadley** [comment]
Given the large number of errors there, I think one class per error is probably too much, so you could have a single `curl_error()` which would contain that error code as a field. In most cases, catching the `curl_error` would allow you to identify that something has gone wrong with the connection, rather than a problem elsewhere in the stack.

**Comment by jeroen** [comment]
We can do something similar as in gert: https://github.com/r-lib/gert/blob/65ca750d4a095af887045fafe64d5e229882be21/R/errors.R

**Comment by jeroen** [comment]
OK this seems to work, also improved the error message a bit. Need to check if this breaks revdeps though.

<img width="848" alt="Screenshot 2024-10-29 at 14 44 17" src="https://github.com/user-attachments/assets/df6b5164-2ecc-407e-9d4b-d15fed38cf6b">
