### ISSUE TITLE
Identify requst in curl_fetch_mutli callback

### ISSUE THREAD

**Issue by fabiangehring** [jeroen/curl#158]
Hi,
Is it possible to add information to parallel requests such that they can be identified in the callback? In my case of post requests the url does not differentiate the requests since they only differ in their body. I did not find a way the "map" the results to the request in the callback function.

Maybe I am missing something?

**Comment by matthijsvanderloos** [comment]
Couldn't you just use function closures for this? For example, the following code performs 5 parallel POST requests with 5 different bodies that can be read in the callback:

```R
> library(curl)
> 
> pool <- new_pool()
> 
> for (i in seq_len(5)) {
+   h <- new_handle()
+   handle_setopt(h, copypostfields = as.character(i));
+   cb <- function() {
+     body <- i
+     function(req){cat("done:", req$url, ": HTTP:", req$status, ": body:", body, "\n")}
+   }
+   curl_fetch_multi("https://httpbin.org/post", done = cb(), pool = pool, handle = h)
+ }
> 
> out <- multi_run(pool = pool)
done: https://httpbin.org/post : HTTP: 200 : body: 3 
done: https://httpbin.org/post : HTTP: 200 : body: 4 
done: https://httpbin.org/post : HTTP: 200 : body: 5 
done: https://httpbin.org/post : HTTP: 200 : body: 1 
done: https://httpbin.org/post : HTTP: 200 : body: 2 
> print(out)
$`success`
[1] 5

$error
[1] 0

$pending
[1] 0
```

**Comment by fabiangehring** [comment]
👍 Nice and easy. Didn‘t think about that! This solves my issue, thx very much.

**Comment by mipelamo** [comment]
I am sorry but I can't find this answer anywhere. I have a similar question, but I need to process the response. How do I do that? 

> library(curl)
> pool <- new_pool()
> req_url <- "https://httpbin.org/post"
> 
>  for (i in 10) {
+   h <- new_handle()
+   body <-jsonlite::toJSON(list(requestAddress = list(addressLine1 = corpAddr_normalize$ADDRS_ONE_TXT[i],
+                                     city =  corpAddr_normalize$CITY_NM[i],
+                                     zipCode5 =  corpAddr_normalize$ZIP_PREFIX_NBR[i])),auto_unbox = TRUE)
+   opts <- list(
+     verbose       = FALSE
+     , post          = TRUE
+     , postfields    = body
+     , postfieldsize = nchar(body)
+   )
+   
+   curl::handle_setopt(h, .list = opts)
+   
+   cb <- function() {
+     
+            function(req){cat("done:", req$url, ": HTTP:", req$status, ": body:", body, "\n")}
+         }
+        curl_fetch_multi(req_url, done = cb(), pool = pool, handle = h)
+ }
> 
> out <- multi_run(pool = pool)


I am trying to make about 500K simultaneous POST request to a single URL, but I need to be read and store the response back. I have taken your code and modified to fit my needs, but I am getting an status 500 code and I am not sure how I store the server's response back.

**Comment by matthijsvanderloos** [comment]
Hi mipelamo,

I'm not sure I get your question. In the callback function the response data is available so you could just store it there, right?
