### ISSUE TITLE
Possible issue with curl on Windows

### ISSUE THREAD

**Issue by leeper** [jeroen/curl#160]
I've received a bug report (https://github.com/cloudyr/aws.s3/issues/237) that appears to trace back to curl on Windows 8, with the core error being:

```R
Error in curl::curl_fetch_memory(url, handle = handle) :
Unrecognized content encoding type. libcurl understands deflate, gzip content encodings.
```

Do you have any idea what the issue is?

**Comment by jeroen** [comment]
It means the server is setting an unusual `Encoding` response header. What do you see if you add `verbose =T` to the handle?

**Comment by leeper** [comment]
Will ask for that info and get back to you.

**Comment by leeper** [comment]
Here's what they're getting: 

```
<- HTTP/1.1 200 OK
<- x-amz-id-2: REMOVED
<- x-amz-request-id: REMOVED
<- Date: Mon, 11 Jun 2018 14:48:42 GMT
<- Last-Modified: Thu, 01 Mar 2018 07:48:37 GMT
<- ETag: REMOVED
<- Content-Encoding: zip
<- Accept-Ranges: bytes
<- Content-Type: application/octet-stream
<- Content-Length: 630
<- Server: AmazonS3
```

**Comment by jeroen** [comment]
That's odd. The server responds with `Content-Encoding: zip` which is [not a valid encoding value](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding).  


The server may only use compression as requested by the client `Accept-Encoding: gzip, deflate`. Does this error not appear on other platforms then?

**Comment by leeper** [comment]
Huh. @dinosupervisor, have you ever encountered this issue on the same machine for any server other than S3?

**Comment by dinosupervisor** [comment]
No, but I do not use the get_object() for other servers. The only thing I noticed is that it appears to work with curl version 3.1, if that could be the reason?

**Comment by jeroen** [comment]
Are you sure it works for curl 3.1? Nothing of that kind has changed.

**Comment by dinosupervisor** [comment]
Ah ok, suddenly it does not work with CURL 3.1 any more as well. I'm actually downloading a zip file, could this have influence?

**Comment by dinosupervisor** [comment]
I tried to download a csv file from the bucket, and that works fine, but for the zip files it does not any more.

**Comment by leeper** [comment]
Does the following work without error:

```R
x <- curl::curl_fetch_memory("https://github.com/jeroen/curl/archive/master.zip")
```

**Comment by jeroen** [comment]
@dinosupervisor can you show me the output from this:
```r
url <- "https://s3.amazonaws.com/rstudio-ide-build/desktop/windows/RStudio-1.2.730.zip"res <- curl::curl_fetch_memory(url, handle = curl::new_handle(nobody=T))curl::parse_headers_list(res$headers)
```

**Comment by dinosupervisor** [comment]
> $`x-amz-id-2`
[1] "xhdBDPXqH7GmP7ctvJuXosiZU59KlC16KFCnoOdTOvWcSAnpLv7i10uY+TdLJWNTSFTWcpCQw6U="

$`x-amz-request-id`
[1] "4C846BC80C8268C1"

$date
[1] "Tue, 12 Jun 2018 13:56:59 GMT"

$`last-modified`
[1] "Mon, 11 Jun 2018 21:36:44 GMT"

$etag
[1] "\"a6eab08220c54715da5f1cc495ff8ceb-21\""

$`accept-ranges`
[1] "bytes"

$`content-type`
[1] "application/zip"

$`content-length`
[1] "168572512"

$server
[1] "AmazonS3"

**Comment by leeper** [comment]
I'm guessing this file was uploaded to S3 with a non-standard `Content-Encoding` value, so it's actually a file-specific issue rather than a curl or aws.s3 issue.

**Comment by dinosupervisor** [comment]
ok thanks so far! I'll talk to our devs who upload the files.
What still puzzles me that downloading zip files does not work any more for the same files, for which it previously worked.

**Comment by jeroen** [comment]
I'm quite sure there must have been a change on the server config that made it stop working. In any case a response header `Content-Encoding: zip` is definitely illegal so this is not a client bug.

**Comment by leeper** [comment]
Thanks, @jeroen. Sorry for troubling you with it.

@dinosupervisor I'll keep the aws.s3 issue open while you check with your team.

**Comment by dinosupervisor** [comment]
@leeper I'll get back to you when I have an update, @jeroen thank you very much for the feedback!

**Comment by muschellij2** [comment]
I'm having the same issue, but **only on Windows**. Appveyor: https://ci.appveyor.com/project/muschellij2/neurovault/builds/29473574#L755

On OSX, working fine:
``` r
url = "https://neurovault.org/media/images/77/zstat-young.nii.gz"
res <- curl::curl_fetch_memory(url, handle = curl::new_handle(nobody=T))
curl::parse_headers_list(res$headers)
#> $server
#> [1] "nginx/1.15.6"
#> 
#> $date
#> [1] "Wed, 11 Dec 2019 17:26:39 GMT"
#> 
#> $`content-type`
#> [1] "application/octet-stream"
#> 
#> $`content-length`
#> [1] "537724"
#> 
#> $connection
#> [1] "keep-alive"
#> 
#> $`last-modified`
#> [1] "Mon, 04 Aug 2014 09:04:35 GMT"
#> 
#> $`content-encoding`
#> [1] "utf-8"
#> 
#> $`strict-transport-security`
#> [1] "max-age=31536000"
#> 
#> $`access-control-allow-origin`
#> [1] "*"
#> 
#> $`access-control-allow-credentials`
#> [1] "true"
#> 
#> $`access-control-allow-methods`
#> [1] "GET, POST, OPTIONS"
#> 
#> $`access-control-allow-headers`
#> [1] "Authorization,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type"
```

<sup>Created on 2019-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

<details>

<summary>Session info</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.0 (2019-04-26)
#>  os       macOS Mojave 10.14.6        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2019-12-11                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version date       lib source                            
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)                    
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.6.0)                    
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)                    
#>  curl          4.2     2019-09-24 [1] CRAN (R 3.6.0)                    
#>  digest        0.6.23  2019-11-23 [1] CRAN (R 3.6.0)                    
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.0)                    
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.6.0)                    
#>  htmltools     0.4.0   2019-10-04 [1] CRAN (R 3.6.0)                    
#>  knitr         1.24.3  2019-08-28 [1] Github (muschellij2/knitr@abcea3d)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)                    
#>  Rcpp          1.0.3   2019-11-08 [1] CRAN (R 3.6.0)                    
#>  rlang         0.4.2   2019-11-23 [1] CRAN (R 3.6.0)                    
#>  rmarkdown     1.16    2019-10-01 [1] CRAN (R 3.6.0)                    
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)                    
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.6.0)                    
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.6.0)                    
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)                    
#>  xfun          0.11    2019-11-12 [1] CRAN (R 3.6.0)                    
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.6.0)                    
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

</details>

**Comment by jeroen** [comment]
It seems to work on my Windows though:

![Screen Shot 2019-12-11 at 9 43 27 PM](https://user-images.githubusercontent.com/216319/70659010-7fcf8a00-1c5f-11ea-8e52-05501a0ab313.png)

**Comment by muschellij2** [comment]
Must be a configuration issue then with Appveyor?
