### ISSUE TITLE
Curl issue windows 10

### ISSUE THREAD

**Issue by Lauler** [jeroen/curl#163]
We are running in to an issue on windows 10 trying to use a Swedish traffic data API ([link](https://www.trafiklab.se/api/resrobot-stolptidtabeller-2)) We're using the `httr` package to make a GET request. On Linux the identical GET request works fine.

```
> httr::GET(url = url, httr::verbose())
-> GET /v2/location.nearbystops.json?key=*EditedOut*&originCoordLat=59.293525&originCoordLong=18.083519 HTTP/1.1
-> Host: api.resrobot.se
-> User-Agent: libcurl/7.59.0 r-curl/3.2 httr/1.3.1
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> 
<- HTTP/1.1 302 Found
<- Date: Wed, 26 Sep 2018 09:30:00 GMT
<- Server: Apache
<- Location: https://api.resrobot.se/v2/location.nearbystops?key=*EditedOut*&originCoordLat=59.293525&originCoordLong=18.083519&format=json
<- Content-Length: 347
<- Content-Type: text/html; charset=iso-8859-1
<- 
-> GET /v2/location.nearbystops?key=*EditedOut*&originCoordLat=59.293525&originCoordLong=18.083519&format=json HTTP/1.1
-> Host: api.resrobot.se
-> User-Agent: libcurl/7.59.0 r-curl/3.2 httr/1.3.1
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> 
<- HTTP/1.1 200 OK
<- Date: Wed, 26 Sep 2018 09:30:00 GMT
<- Server: Jetty(8.1.16.v20140903)
<- Content-Type: application/json; charset=UTF-8
<- Cache-Control: max-age=0,no-cache,no-store
<- Content-Encoding: UTF-8
<- Transfer-Encoding: chunked
<- 
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Unrecognized content encoding type. libcurl understands deflate, gzip content encodings.
```

We've seen this issue referenced before in #160 , but are not too well versed with curl to know how to trouble shoot things. Also we suspect this might be an odd and obscure issue. 

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Swedish_Sweden.1252  LC_CTYPE=Swedish_Sweden.1252    LC_MONETARY=Swedish_Sweden.1252
[4] LC_NUMERIC=C                    LC_TIME=Swedish_Sweden.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] jsonlite_1.5

loaded via a namespace (and not attached):
[1] httr_1.3.1     compiler_3.5.1 R6_2.2.2       tools_3.5.1    curl_3.2       yaml_2.2.0 
```

Any ideas on what might be going wrong? Can share key in private if you need to test.

**Comment by jeroen** [comment]
This is a bug in the webserver. It responds with `Content-Encoding: UTF-8` which is an unknown value for that header. The best fix would be to reach out to who is providing this service and have it fixed on their end.

Perhaps you can trick the server into giving the right response by overriding the `Accept-Encoding` header with:

```r
httr::GET(url = url,  config(accept_encoding="identity"))
```

**Comment by Lauler** [comment]
The webserver responds with the same Content-Encoding no matter the OS. From what we can see the only difference is that httr in our Linux Mint uses an older version of libcurl. Linux uses libcurl/7.47.0 whereas windows uses libcurl/7.59.0 for the request. 

For some reason `Content-Encoding: UTF-8` does not produce the same error on Linux. 

The workarounds did not work in tricking the server. Same when unsetting. Thanks for the help. We have notified the maintainers of the API. Although it seems strange you can get the content fine typing the link in to a browser or on linux (with the same unknown value for the `Content-Encoding`) but not on windows.

**Comment by jeroen** [comment]
Did the link also work in Internet Explorer on Windows? I think it's the Windows crypto back-end that trips over it.

**Comment by Lauler** [comment]
Works fine in both IE11 and Microsoft Edge.
