### ISSUE TITLE
R connection is not destroyed on error

### ISSUE THREAD

**Issue by gaborcsardi** [jeroen/curl#165]
Seems like it is possible that `curl()` creates a connection, but then it errors out, and the connection is  not destroyed. E.g.

```r
> cx <- curl::curl("https://ipv6.test-ipv6.com", open = "r")
Error in open.connection(con, open = mode) : Couldn't connect to server
> showConnections(all =  TRUE)
  description                  class      mode text   isopen   can read can write
0 "stdin"                      "terminal" "r"  "text" "opened" "yes"    "no"
1 "stdout"                     "terminal" "w"  "text" "opened" "no"     "yes"
2 "stderr"                     "terminal" "w"  "text" "opened" "no"     "yes"
3 "https://ipv6.test-ipv6.com" "curl"     "r"  "text" "closed" "yes"    "no"
> x <- gc()
Warning message:
In .Internal(gc(verbose, reset, full)) :
  closing unused connection 3 (https://ipv6.test-ipv6.com)
```

I would like to avoid the warning, if possible.

This is curl 3.2 on Linux, on a host that does not have IPV6 access to `ipv6.test-ipv6.com`. Let me know if you need more info.

**Comment by jeroen** [comment]
Hmm interesting. If you manually open, then `base::url` does the same:

```r
cx <- base::url("https://ipv6.test-ipv6.com")
open(cx)
rm(cx)
gc()
```

So perhaps all that is needed is add a tryCatch to `curl()`.

**Comment by gaborcsardi** [comment]
Yeah, that seems right. 

If you re-throw the error, then the error stack will not include  `curl_connection`, though, which a minor glitch, in case you want to fix it. This probably fixes it: 

```r
    withCallingHandlers(open(con, open = mode), error = function(err) {
      close(con)
    })
```

**Comment by jeroen** [comment]
OK I changed this. 

The proper solution may be to make the `rcurl_open()` callbak return `FALSE` instead of `Rf_error()` so that R doesn't mark the connection as open. However then we cannot throw a custom error message.
