### ISSUE TITLE
Conditions thrown from callbacks are lost

### ISSUE THREAD

**Issue by gaborcsardi** [jeroen/curl#168]
Because the callbacks run in another top level R expression. I am not sure if this is a bug, or even if we can do anything about it, but it does cause some inconveniences for me, as my progress bars are implemented with conditions.

Is there an alternative to the top level exec? 
* Newer R versions have a C API for `tryCatch()`.
* Maybe we can wrap the user supplied R function in a `tryCatch()`, that catches errors, but let's the rest through.

**Comment by jeroen** [comment]
The multi callbacks do not run in a top level expression actually but are evaluated in the current context. Only the progress callbacks are evaluated on the top level:
```r
m <- new_pool()
curl_fetch_multi('https://httpbin.org/get', done = function(...){
  stop("Oh no an error")
}, pool = m)
multi_run(pool = m)

```

**Comment by gaborcsardi** [comment]
I am not sure why that is, but yeah, I use the progress callback, to create a progress bar for all multi downloads.

Would it make sense to do the same for the progress callback?

**Comment by gaborcsardi** [comment]
Is there a specific reason for running the progress callback as a new top level expression? Just to continue on errors?

**Comment by jeroen** [comment]
It's partly historical because the progress callbacks predate the multi api. 

But also it may be dangerous to use the callback to perform a jump from within the regular synchronous api. It may leave the request and perhaps the entire libcurl in  an undefined state if during a transfer it invokes a simple progress callback that then never returns.

I think you can abort the transfer from the callback by returning FALSE in the progress callback. This will still give curl the opportunity to abort the transfer and clean up, before raising an error.

**Comment by gaborcsardi** [comment]
True, but I don't actually want to raise an error, I want to throw a non-error condition, a `message()` basically.

**Comment by jeroen** [comment]
Mmm okay. I'm not entirely confident about how safe it is to call the R api from these libcurl callbacks, I don't control when/where they get invoked. Perhaps they could get called from another thread on some systems? 

If we move away from `R_tryEval` we also need to deal with interrupts and timeouts that can happen during the R callback. We really don't want to jump.

**Comment by gaborcsardi** [comment]
Bit then how about erroring in the multi callbacks? Isn't that the same? 

Anyway, if you don't want to change it, that's fine, I think I can work around it.

**Comment by jeroen** [comment]
The `cb_complete` and `cb_error` functions are called by my own when looping over the results at a point where it is safe to error: https://github.com/jeroen/curl/blob/master/src/multi.c#L148-L155. So this is different from the libcurl callback mechanism.

**Comment by gaborcsardi** [comment]
I meant the data callback, sorry. That has to be able to error, because the
output file might error, etc.

**Comment by jeroen** [comment]
If you error in your data callback, you cannot catch the error message indeed. It will be printed to the console by `R_tryEval()`, which then aborts the transfer by returning 1 in the callback. So if you do this you will get a `CURLE_ABORTED_BY_CALLBACK` error when calling `multi_run()`.
