### ISSUE TITLE
New $content_type member

### ISSUE THREAD

**Issue by gaborcsardi** [jeroen/curl#169]
In the rare case when the response does not have a `content` member, this is problematic, because `response$content` does partial matching and selects the new `content_type` member. Before `response$content`  was `NULL`.

Maybe you could always add a `content = NULL` member? Although  that might break some existing code as well, if people do `"content" %in% names(response)`,  but I  would guess that this is even more rare.

**Comment by gaborcsardi** [comment]
Actually, this might be my bad, don't worry about it.

**Comment by jeroen** [comment]
It turn
