### ISSUE TITLE
Install from source on MacOS fails

### ISSUE THREAD

**Issue by cortinah** [jeroen/curl#171]
Hello, I'm trying to install curl from source on MacOS Mojave so that it can add support for the sftp protocol.  I've updated libcurl using homebrew and the updated curl binary does indeed now support sftp.   However, I am not getting the R curl package to install so it can integrate sftp.  I included the homebrew curl directories to my PATH, but something is still off.   Any help would be appreciated.  thank you very much.

> install.packages("curl", type = "source")
trying URL 'https://cran.rstudio.com/src/contrib/curl_3.2.tar.gz'
Content type 'application/x-gzip' length 367047 bytes (358 KB)
==================================================
downloaded 358 KB

* installing *source* package ‘curl’ ...
** package ‘curl’ successfully unpacked and MD5 sums checked
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-I/usr/local/Cellar/curl/7.62.0/include
Using PKG_LIBS=-L/usr/local/Cellar/curl/7.62.0/lib -lcurl
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libcurl was not found. Try installing:
 * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 * rpm: libcurl-devel (Fedora, CentOS, RHEL)
 * csw: libcurl_dev (Solaris)
If libcurl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libcurl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘curl’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/curl’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/curl’
Warning in install.packages :
  installation of package ‘curl’ had non-zero exit status

**Comment by astrophys** [comment]
See related : [question](https://stackoverflow.com/questions/53913019/installing-curl-package-in-r-3-5-1) on stackoverflow.  On 10.13.6, I was able to install `curl` by downgrading R to v.3.4.2.  This means having a separate installation for R-3.4.2.  FYI, when installing R from source on OSX, you'll want to set all the compilers to clang or clang++, i.e. 

`export OBJC=/usr/bin/clang; export CC=/usr/bin/clang; export CXX=/usr/bin/clang++; ./configure --prefix=/Users/username/.local/`

Then run `make`, `make install`.  This is not a solution, but at least temporary work around.
