### ISSUE TITLE
Honor `getOption("timeout")`

### ISSUE THREAD

**Issue by vspinu** [jeroen/curl#173]
I am occasionally seeing the following timeout error with read_html on a slow server:

```
Error in open.connection(x, "rb") : 
  Timeout was reached: Operation timed out after 10001 milliseconds with 0 out of 0 bytes received
```

It looks like the timeout is currently [hardcoded](https://github.com/jeroen/curl/blob/5be4dcc77186b8b4572c18608d948c42260a4194/src/curl.c#L106). Would it be possible to add an option or honor `options("timetout")`?

(Originally posted on [`xml2` tracker](https://github.com/r-lib/xml2/issues/242))

**Comment by jeroen** [comment]
I don't think that's a good idea. R's default of 60 is too high, and timeout is typically something that you want to control per host/application. When using a global options, different packages depending on curl will each start overwriting this option with their preference.

What is the reason that you want more than 10 sec timeout? It seems very unlikely that the host is suddenly going to repsond if you wait another 50 sec.

**Comment by vspinu** [comment]
Why would packages overwrite the default? Options are for users only. And even if they do overwrite dynamically for their own localized reasons, I don't see how that would be worse than the current situation. 

> What is the reason that you want more than 10 sec timeout? It seems unlikely that the host is suddenly going to respond if you wait another 50 sec.

Well, in my case it's very likely. I commonly see 5-10 sec response times. I am scrapping a slow web site and I do see a 10sec timeout every 50 pages or so.

**Comment by ShixiangWang** [comment]
I also want an option to handle this. I dont know how to fix timeout problem.

```
> gse <- getGEO('GSE10')
Error in open.connection(x, "rb") : 
  Timeout was reached: Resolving timed out after 10000 milliseconds
> gse <- getGEO('GSE10')
Error in open.connection(x, "rb") : 
  Timeout was reached: Resolving timed out after 10000 milliseconds
> gse <- getGEO('GSE10')
Error in open.connection(x, "rb") : 
  Timeout was reached: Resolving timed out after 10000 milliseconds
> gse <- getGEO('GSE10')
Error in open.connection(x, "rb") : 
  Timeout was reached: Resolving timed out after 10000 milliseconds
```

following code make the program stop.

```
> con <- curl::curl("https://ftp.ncbi.nlm.nih.gov/geo/series/GSEnnn/GSE10/matrix/") 
> readLines(con)
Error in readLines(con) : 
  Timeout was reached: Resolving timed out after 10000 milliseconds
```

I google everywhere I can, but cannot find a way.

`curl` in terminal works, it basically takes more then 10s.

```
$ /opt/anaconda3/bin/curl "https://ftp.ncbi.nlm.nih.gov/geo/series/GSEnnn/GSE10/matrix/"
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
 <head>
  <title>Index of /geo/series/GSEnnn/GSE10/matrix</title>
 </head>
 <body>
<h1>Index of /geo/series/GSEnnn/GSE10/matrix</h1>
<pre>Name                       Last modified      Size  <hr><a href="/geo/series/GSEnnn/GSE10/">Parent Directory</a>                                -   
<a href="GSE10_series_matrix.txt.gz">GSE10_series_matrix.txt.gz</a> 2019-01-25 09:32  355K  
<hr></pre>
</body></html>
```

**Comment by jeroen** [comment]
You can set the timeout in the handle:

```r
h <- curl::new_handle(timeout = 60)
con <- curl::curl("https://ftp.ncbi.nlm.nih.gov/geo/series/GSEnnn/GSE10/matrix/", handle = h) 
readLines(con)
```

**Comment by ShixiangWang** [comment]
@jeroen Thanks for your quick reply and solution. I did work for this `curl` code. However, it cannot apply to `GEOquery::getGEO()`. I just found why curl is so slow in my linux server - Slow DNS on Linux fix (ipv6/ipv4 conflict).  I followed <https://aarvik.dk/disable-ipv6/> and time of running code can be reduced to about 5s, thus the problem is fixed.

Thanks again.
