### ISSUE TITLE
Fetching properties/attributes for files in an FTP folder

### ISSUE THREAD

**Issue by NZambranoc** [jeroen/curl#176]
I've been trying to extract the modified full-timestamp from a list of files in an FTP folder using the curl package in R. All I've managed to extract is a partial DateTime. The problem is the strings from which I'm going to extract the timestamps are automatically re-formatted if they were last modified within the last year.

[Here's a SO thread describing the problem + an example](https://stackoverflow.com/questions/54752881/fetching-properties-attributes-for-files-in-an-ftp-folder-using-r-and-the-curl-p
)

**Comment by Hong-Revo** [comment]
I don't think curl can do anything about this. That's just how the ftp server formats the directory listing.
