### ISSUE TITLE
curl_download error

### ISSUE THREAD

**Issue by fm555** [jeroen/curl#180]
I am experiencing an error to download a csv file from a password protected site, when using curl_download.

I am using:

h<- curl::new_handle()
curl::handle_setopt(
handle=h,
httpauth=1,
userpwd = "Part1\\Part2:mypassword",
verbose=TRUE
)

Where my username is something similar to "Part1\\Part2" (oiriginally Part1\Part2, but I had to include two "\\" in R), and my password is something similar to "mypassword".

I use filename to specify the path wheer I want to save the csv file:
filename="C:/Documents"

The link of the csv file is something similar to: 
csv_link="http//very_long_link_to_csv"

I run curl_download:

curl_download(csv_link,destfile=filename,handle=h)

But it gives the following error (I am copying the text but after editing some info with *, and also username, links, etc...):

*   Trying *.*.*.*...
* TCP_NODELAY set
* Connected to proxy.*.* (*.*.*.*) port 80 (#0)
* Server auth using Basic with user 'Part1\Part2'
> GET  http//very_long_link_to_csv HTTP/1.1
Host: *.*.*
Authorization: Basic *****************************
User-Agent: R (3.5.0 x86_64-w64-mingw32 x86_64 mingw32)
Accept: */*
Accept-Encoding: gzip, deflate
Proxy-Connection: Keep-Alive

< HTTP/1.1 401 Unauthorized
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< Transfer-Encoding: chunked
< Cache-Control: proxy-revalidate
< Proxy-Connection: Keep-Alive
< Connection: Keep-Alive
< Proxy-support: Session-based-authentication
< Date: Thu, 21 Mar 2019 12:07:58 GMT
< 
* Connection #0 to host proxy*.* left intact
Error in curl_download(url_file_csv, destfile = filename, handle = h) : 
  HTTP error 401.

I am using proxy connection, using a Renviron file with the proxy configuration.

Could you please help me to solve this sissue so I can download the csv file with curl_download?

My sessionInfo() information:

R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                   LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] curl_3.2   httr_1.3.1

loaded via a namespace (and not attached):
[1] compiler_3.5.0 R6_2.2.2       tools_3.5.0    yaml_2.1.19

My  curl::curl_version() information:

curl::curl_version()
$`version`
[1] "7.59.0"

$ssl_version
[1] "(OpenSSL/1.0.2n) WinSSL"

$libz_version
[1] "1.2.8"

$libssh_version
[1] "libssh2/1.8.0"

$libidn_version
[1] NA

$host
[1] "x86_64-w64-mingw32"

$protocols
 [1] "dict"   "file"   "ftp"    "ftps"   "gopher" "http"   "https"  "imap"   "imaps"  "ldap"   "ldaps"  "pop3"   "pop3s"  "rtsp"   "scp"    "sftp"   "smtp"  
[18] "smtps"  "telnet" "tftp"  

$ipv6
[1] TRUE

$http2
[1] FALSE

$idn
[1] TRUE

**Comment by jeroen** [comment]
I cannot reproduce the problem (but I don't have a proxy server). If I test basic auth with a standard server it works both for `curl_fetch_memory()` and `curl_download()`.

```r
h<- curl::new_handle()
curl::handle_setopt(
  handle=h,
  httpauth=1,
  userpwd = "jerry:secret",
  verbose=TRUE
)
url <- "https://www.httpbin.org/basic-auth/jerry/secret"
req <- curl::curl_fetch_memory(url, handle = h)
curl::curl_download(url, tempfile(), handle = h)
```

There might be a problem in your proxy server or with the server you are downloading from. Would it be possible to test if you can download the same file if you are not behind the proxy server?

**Comment by jeroen** [comment]
Also can you try __without__ setting `httpauth=1` in your handle, because that should not be needed.

**Comment by fm555** [comment]
I have tried without setting httpauth=1 in my handle but gives the same error (http error 401). 

I have tried in another laptop without proxy connection (both with  httpauth=1 and without) and gives the same error:

*   Trying *.*.*.*...
* TCP_NODELAY set
* Connected to *.*.* (*.*.*.*) port 80 (#0)
> GET  link_to_csv HTTP/1.1
Host: very_long
User-Agent: R (3.5.2 x86_64-w64-mingw32 x86_64 mingw32)
Accept: */*
Accept-Encoding: gzip, deflate

< HTTP/1.1 401 Unauthorized
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< Transfer-Encoding: chunked
< 
* Connection #0 to host*.*.* left intact
Error in curl_download(url_file_csv, destfile = filename, handle = h) : 
  HTTP error 401.

I have realised that the GET in the error message in the previous case had all the http//very_long_link_to_csv, but in this case the GET does not include the part of the host. Not sure if this is an important detail or not, but just in case.

Any suggestion?
Do I need to try different configuration options?

**Comment by fm555** [comment]
I tried with my laptop without proxy and curl_download is giving this error:

* Could not resolve host: link_to_login_for_the_csv
* Closing connection 0
Error in curl_download(url_file_csv, destfile = filename, handle = h) : 
  Could not resolve host: link_to_login_for the_csv

"link_to_login_for_the_csv" refers to the link where you should provide the username and password to access the csv file.

Any suggestion about how to solve this isue? 
Do I need to use additional authentication parameters to download the csv file with curl_download?
Is it possible to know if I am using the correct authentication parameters?

**Comment by jeroen** [comment]
So it is treating the username as the host??! Can you add the `verbose=TRUE` output?

Perhaps instead of setting `userpwd` options you can set the [username](https://curl.haxx.se/libcurl/c/CURLOPT_USERNAME.html) and [password](https://curl.haxx.se/libcurl/c/CURLOPT_PASSWORD.html) options (i.e. set them separately)?

**Comment by jeroen** [comment]
You can also try encoding the password in `curl::curl_escape` see if that helps.
