### ISSUE TITLE
libcurl is built without the HTTPS-proxy support

### ISSUE THREAD

**Issue by danielsjf** [jeroen/curl#186]
I'm trying to run the function below on Windows. I'm using a HTTPS proxy, but apparently that isn't supported by libcurl.

```
curl::curl_fetch_memory("google.com")
Error in curl::curl_fetch_memory("google.com") : 
  Unsupported proxy 'https://xx.xx.xx.xx:xx', libcurl is built without the HTTPS-proxy support.
```

Is there any way to use the HTTPS proxy?

Unfortunately, I'm not really sure where the original proxy is set, but I tried a few methods to get around it:
* Set a non HTTPS version in the path -> still the old one
* Set the proxy via the rcurl options -> still the old one
```
opts <- list(
  proxy         = "http://xx.xx.xx.xx",
  proxyport     = xx
)
options(RCurlOptions = opts)
```
* Use httr -> still the old one
```
set_config(
  use_proxy(url="http://xx.xx.xx.xx", port = xx)
)
```

So I was also wondering where else the proxy could come from.

**Comment by danielsjf** [comment]
Somehow, the proxy was still in my environment. Using Sys.setenv(HTTP_PROXY='http://xx.xx.xx.xx:xx') solved that problem.

That still leaves the question if HTTPS is supported at all.

**Comment by jeroen** [comment]
@bagder we have a windows built with dual ssl (schannel + openssl) but still this user is getting `libcurl is built without the HTTPS-proxy support.`. Is this expected?

**Comment by dmi3kno** [comment]
@danielsjf are you sure the right `curl` is used? Do you see anything when you run `where curl` in command line?

**Comment by bagder** [comment]
The Schannel backend doesn't support HTTPS proxy I think. The OpenSSL should work fine.

**Comment by dmi3kno** [comment]
I think I asked in another thread some time ago, but is there  a simple way to disable [revocation check](https://github.com/curl/curl/commit/172b2beba6b89b632c09be7a88645e3a0607cfe9)?

**Comment by danielsjf** [comment]
@dmi3kno,

Not sure what the expected answer is, but when I run `where curl`, I get the following error.

```
C:\XXX>where curl
INFO: Could not find files for the given pattern(s).
```

**Comment by Fredo-XVII** [comment]
> Somehow, the proxy was still in my environment. Using Sys.setenv(HTTP_PROXY='http://xx.xx.xx.xx:xx') solved that problem.
> 
> That still leaves the question if HTTPS is supported at all.

Thanks! I had my env variable in lower case, when it should have been in upper case.

**Comment by Shaunson26** [comment]
I had this issue attempting to connect to sharepoint sites using Microsoft365R .. I got my IE proxy ('myproxy') using curl, and then used Sys.setenv(https_proxy='http://myproxy') and it worked ? that is, i set my HTTPS proxy with a HTTP address ?

**Comment by jay** [comment]
> that is, i set my HTTPS proxy with a HTTP address ?

[https_proxy](https://curl.se/docs/manpage.html#HTTPSPROXY) env var contains the proxy that libcurl will use for https:// URLs. It's fine if it's an HTTP proxy. It may be an HTTPS proxy if your build of r curl supports that. However, I don't know if Sys.setenv is the preferred way to set a proxy for r curl.
