### ISSUE TITLE
Proper runtime type checking for option values

### ISSUE THREAD

**Issue by jeroen** [jeroen/curl#188]
We need to do a better job type checking option values. See for example https://github.com/jeroen/curl/issues/162

The `typecheck-gcc.h` header contains this information in e.g. `_curl_is_slist_option(option)` but these macro's are only available on gcc 4.3 and clang seems to be defined as 4.2. This seems to work in clang though:

```c
#undef __GNUC_MINOR__
#define __GNUC_MINOR__ 3

#include <curl/curl.h>

_curl_is_slist_option(CURLOPT_VERBOSE);

```

@bagder is there a programatic way to know at runtime which type of argument a given `CURLOPT_xyz` requires? Why are these macros disabled for clang?

**Comment by jeroen** [comment]
@bagder is there programatic way to know if a given `CURLOPT_xyz` option requires a `const char*` or a `struct curl_slist *` argument?

**Comment by bagder** [comment]
No...

The ones accepting a "string" are all using `STRINGPOINT` in the header so it is at least possible to generate a list from that.

**Comment by jeroen** [comment]
@bagder I have updated my initial question. Why is type-checking not included for clang? It seems to work? https://github.com/curl/curl/blob/master/include/curl/curl.h#L2854-L2858

**Comment by bagder** [comment]
Nobody has enabled them for clang, obviously. As for why? Busy with other things? People don't care? People don't know how? Combinations of all three?

**Comment by jeroen** [comment]
OK so I might start a discussion about this upstream.

**Comment by jeroen** [comment]
@bagder If I want to start using the type checking macros in the bindings, and I am willing to assume a recent enough gcc or clang, would including `typecheck-gcc.h` explicitly likely be past/future proof?

```c
#include curl.h
#ifndef __CURL_TYPECHECK_GCC_H
#include <curl/typecheck-gcc.h>
#endif
```

**Comment by jeroen** [comment]
We mostly have this now in https://github.com/jeroen/curl/blob/master/src/typechecking.c. Need to do more checking on if this will cause problems for non-gcc compilers.
