### ISSUE TITLE
Add URL to timeout error message

### ISSUE THREAD

**Issue by mattdowle** [jeroen/curl#190]
Hi,
curl usually works great and we all completely rely on it.  Today I hit a rare problem that I tweeted about ([here](https://twitter.com/MattDowle/status/1153411113838469120)) in case someone else knows what the URL is that it is timing out on in this case.  In general, it would be great if the error message including the URL that it was timing out on. For cases like this where all I see is a log file.
![image](https://user-images.githubusercontent.com/2779998/61666041-6798a780-ac8b-11e9-82f9-2a61be4fe4f3.png)
I'm trying to create a PR to curl to do this. I searched this repo for the string "timed" to find the error message but nothing came up. Then I searched this repo for "curl_fetch_memory" and I found lots of usage but, oddly, not where it is defined. I'll keep trying.
Could you give me some hints as to where I might modify the code to include the URL in the timeout error message?
Thanks, Matt

**Comment by krlmlr** [comment]
Perhaps in `assert_status()` ? Looks like the error message comes from libcurl.

https://github.com/jeroen/curl/blob/1d9ba653019eccbe12160eb480be7861a4ebe2ab/src/utils.c#L44-L49

**Comment by mattdowle** [comment]
Thanks for the tip, @krlmlr!  I was able to trace it though from there and filed the PR.

**Comment by mattdowle** [comment]
I just saw the same timeout again. Is there anything else you'd like me to do in PR #191?
![image](https://user-images.githubusercontent.com/2779998/62815679-c6a24d00-bad0-11e9-8cd7-9b03c5475582.png)

**Comment by jeroen** [comment]
Fix on CRAN now.

**Comment by mattdowle** [comment]
Great. Thanks, Joroen!

**Comment by krlmlr** [comment]
Can we also include the hostname in generic error messages? Seeing travis build failures from pkgdown.

https://travis-ci.org/github/krlmlr/dm/jobs/677591111#L1151
