### ISSUE TITLE
Including smtp:// in smtp_server parameter

### ISSUE THREAD

**Issue by datawookie** [jeroen/curl#195]
Hi @jeroen,

I'm trying to debug issue from @rdatasculptor on `{emayili}`. However in the process we have uncovered something about `{curl}` which has us puzzled.

When @rdatasculptor sends mail like this it works:

```
send_mail(..., smtp_server = "smtp://mail.happyatwork.nl")
```

This is puzzling because `send_mail()` actually adds `smtp://` to the beginning of the URL.

However, when he sends mail like this it fails:

```
send_mail(..., smtp_server = "mail.happyatwork.nl")
```

Now the interesting thing is that in these two situations the function actually ends up talking to a different machine. In the first case the server resolves to 93.95.2.120, but in the second case it resolves to 93.95.0.156.

Do you have any idea what might be going on? Why would those two resolve to different IP addresses?

Thanks,
Andrew.

**Comment by jeroen** [comment]
So can you try to `debug(curl::curl_fetch_memory)` and then see what the actual `url` is that is being used?

**Comment by jeroen** [comment]
It sounds like in the first case you end up using `smtp://smtp://mail.happyatwork.nl` as the server. I should make a check in the package to make sure that is caught.

I don't know why, but from the verbose output it seems that libcurl interprets a URL that starts with `smtp://smtp://......` to just `smtp`. Hence the host gets resolved to the ip address is the same as your local `smtp` hostname. Try:

```
ping smtp
```

It depends on your network configuration what host `smtp` resolves to but usually it is a local smtp server from your company or ISP.

**Comment by datawookie** [comment]
Aha! That makes complete sense.

@rdatasculptor can you please try both of the following:

$ ping smtp
$ ping mail.happyatwork.nl

Thanks!

**Comment by datawookie** [comment]
@jeroen thanks for the quick fix. :+1:

**Comment by rdatasculptor** [comment]
Yes thank you! 
I guess I need to reinstall the dev version of `curl`. Because our system has difficulties to use RTools, this will be a bit of problem. But as soon I could install, I will let you know if the fix was a success.

**Comment by datawookie** [comment]
@rdatasculptor would you mind doing the two quick `ping` tests I mentioned above? I think that should clarify the underlying source of the strange behaviour. Thanks.

**Comment by rdatasculptor** [comment]
Oh yes, ofcourse.
Because of restrictions on our system (....), I can't do it otherwise: I used `pingr` package for this.

```
library(pingr)

ping("smtp")
ping("mail.happyatwork.nl")

> ping("smtp")
[1] NA NA NA
> ping("mail.happyatwork.nl")
[1]  1 NA NA
```

Actually, I an not sure if this was helpful. Do you need other/additional information?

**Comment by datawookie** [comment]
Hmmm. Not sure that is very helpful. Can you try the following:

```
library(curl)

nslookup("smtp")
nslookup("mail.happyatwork.nl")
```

Thanks!

**Comment by jeroen** [comment]
@rdatasculptor if you send the email with `verbose = TRUE` (the default) the output should tell you what host it is (trying to) connect to.

**Comment by datawookie** [comment]
This is a good point. And try just using `"smtp"` as the name of the server rather than `"smtp://mail.happyatwork.nl"` (which won't work with most recent version of `{curl}`).

**Comment by rdatasculptor** [comment]
When I run `send_mail()` with  just "smtp" it tries to connect to 93.95.2.215 (for the record, I haven't been able to install the latest dev version of curl, because of RTools-restrictions in our network)
When I run `send_mail()` with  "mail.happyatwork.nl" it tries to connect to 93.95.0.156

Okay, and now this:

```
nslookup("smtp")
[1] "93.95.2.120"
> nslookup("mail.happyatwork.nl")
[1] "93.95.0.156"

```

So there seem three different ip-addresses now :-)

**Comment by datawookie** [comment]
Aha! Okay, now we are getting somewhere. I think that the situation is (as @jeroen surmised) that when you used `smtp://mail.happyatwork.nl` as the server address, the *old* version of `{curl}` was converting that into `smtp://smtp://mail.happyatwork.nl`, which was ultimately just interpreted as `smtp`. This is a machine name on your *local* network.

Can you please try using `smtp` as the server name with `{emayili}`? I suspect that you'll find that this works.

**Comment by rdatasculptor** [comment]
Using `smtp` works in `{emayili}`!
