### ISSUE TITLE
schannel: CertGetNameString() failed to match connection hostname against server certificate names

### ISSUE THREAD

**Issue by giuseppec** [jeroen/curl#196]
After updating `curl` to version 4.0, I get the following error:
```r
library(httr)
GET("https://www.openml.org")
# Error in curl::curl_fetch_memory(url, handle = handle) : 
#   schannel: CertGetNameString() failed to match connection hostname (www.openml.org) against server certificate names
```
with older curl versions, it works. Any hints I could do to fix this?

**Comment by jeroen** [comment]
Sounds like a duplicate of https://github.com/jeroen/curl/issues/193.

Try installing the latest version of httr:

```r
remotes::install_github("r-lib/httr")
```

**Comment by giuseppec** [comment]
Thx. This seems to solve the issue.

**Comment by denislepage** [comment]
I am getting possibly a related error linked to certificates with the latest curl built.

```
	url <- "https://sandbox.motus.org/api/sgdata/custom/authenticate_user"
	query <- list("user" = "motus.sample", "password" = "motus.password")
	json <- jsonlite::toJSON(query, auto_unbox = TRUE, null = "null")
	ua <- httr::user_agent(agent = "https://github.com/MotusWTS/motus")
		
	# Set curl options
	httr::set_config(httr::accept_json())
	httr::set_config(httr::content_type_json())
	
	httr::POST(url, body = list("json" = json), encode = "form",
		httr::config(http_content_decoding = 0), ua, 
		httr::timeout(120))

	# test curl alone, without parameters
	curl::curl_fetch_memory(url)
```

Error in curl::curl_fetch_memory(url, handle = handle) : 
  schannel: CertGetNameString() failed to match connection hostname (sandbox.motus.org) against server certificate names

the second call directly to curl_fetch_memory doesn't suffer from the same problem.

This server has a certificate with several altnames, so I am curious if this error relates to this:
https://github.com/curl/curl/issues/3711

This error happens with latest curl version 7.64.1, but not with earlier version 7.56 still relying on WinSSL on a different computer.

> curl::curl_version()
$version
[1] "7.64.1"

$ssl_version
[1] "(OpenSSL/1.1.1a) Schannel"

I am using R on Windows 7 Pro 64 bits.

**Comment by jeroen** [comment]
@denislepage can you please try with the latest `httr`:

```r
remotes::install_github("r-lib/httr")
```

**Comment by denislepage** [comment]
Ah... Thanks! That did it. That was almost too easy, sorry for the trouble. We're about the release some code for users, so it's good to have the fix at hand.
