### ISSUE TITLE
Version mismatch with system

### ISSUE THREAD

**Issue by midickinson** [jeroen/curl#200]
System is Ubuntu 18.04.2 LTS

My Goal is to get sftp transfers working. Learned the Ubuntu does not have ssh enabled, I did the steps to reinstall libssh and curl from source on the machine. 

`$ curl -V
curl 7.65.3 (x86_64-pc-linux-gnu) libcurl/7.65.3 OpenSSL/1.1.1 zlib/1.2.11 libssh2/1.9.0-20190820
Release-Date: 2019-07-19
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtp
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
`
Everything checks out on the system. 

But in R, the curl version does not match.  I have reinstalled curl package from source, and rebooted.  On version 4.0.  

This is opening R interface in shell
`
> curl::curl_version()
$version
[1] "7.58.0"

$ssl_version
[1] "OpenSSL/1.1.1"

$libz_version
[1] "1.2.11"

$libssh_version
[1] NA

$libidn_version
[1] "2.0.4"

$host
[1] "x86_64-pc-linux-gnu"

$protocols
 [1] "dict"   "file"   "ftp"    "ftps"   "gopher" "http"   "https"  "imap"
 [9] "imaps"  "ldap"   "ldaps"  "pop3"   "pop3s"  "rtmp"   "rtsp"   "smb"
[17] "smbs"   "smtp"   "smtps"  "telnet" "tftp"
`
Making things even odder is that this server is also the host for RStudio-Server,  going in through the web IDE.  This uses the same package library and version.  I do show the correct version of curl install. 

`
> curl::curl_version()
$version
[1] "7.65.3"

$ssl_version
[1] "OpenSSL/1.1.1"

$libz_version
[1] "1.2.11"

$libssh_version
[1] "libssh2/1.9.0-20190820"

$libidn_version
[1] NA

$host
[1] "x86_64-pc-linux-gnu"

$protocols
 [1] "dict"   "file"   "ftp"    "ftps"   "gopher" "http"   "https"  "imap"   "imaps"  "pop3"   "pop3s"  "rtsp"   "scp"    "sftp"   "smb"    "smbs"   "smtp"   "smtps"  "telnet" "tftp"  

$ipv6
[1] TRUE

$http2
[1] FALSE

$idn
[1] FALSE
`

**Comment by jeroen** [comment]
You probably need to start R with:

```sh
export LD_LIBRARY_PATH=/usr/local/lib
R
```

**Comment by tahsinalamin** [comment]
Still not working for me. Did this problem get fixed?

**Comment by jeroen** [comment]
You are probably still loading the old shared library. Try setting `LD_LIBRARY_PATH` or `R_LD_LIBRARY_PATH` to the directory of your new library. See also section 3.6.3 of the [R administration manual](https://cran.r-project.org/doc/manuals/r-release/R-admin.html).

**Comment by tahsinalamin** [comment]
It worked for me:

```
which curl //get the path
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/bin
sudo ldconfig
```
