### ISSUE TITLE
Windows error: Failure when receiving data from the peer

### ISSUE THREAD

**Issue by tylerlittlefield** [jeroen/curl#206]
I'm writing a package that talks to an API, I'm using `httr::GET` and noticed this is failing on Windows. I first found out when the appveyor builds started to fail. I've since tested the following example on a Windows machine and can reproduce the issue:

``` r
library(curl)

x <- "https://exoplanetarchive.ipac.caltech.edu/cgi-bin/nstedAPI/nph-nstedAPI?table=exoplanets&select=pl_hostname,ra,dec"
curl_fetch_memory(x)
#> Error in curl_fetch_memory(x): Failure when receiving data from the peer
```

<sup>Created on 2019-09-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Is there something special I need to do to resolve this issue on Windows?

Session info:

```r
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] curl_4.2

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1    packrat_0.5.0 
```

**Comment by jeroen** [comment]
Hmm it seems a bug in the libcurl schannel backend. As a temporary workaround you can try switching to the openssl backend as described [here](https://cran.r-project.org/web/packages/curl/vignettes/windows.html)

**Comment by tyluRp** [comment]
Interesting! Thanks a bunch for digging into this. I think for now, I will revert back to how I used to pull the data instead of using `httr` at the moment. Thanks again!

**Comment by Jeremy-DX** [comment]
This error may be caused by your local VPN. When I close my local VPN, it works again.

**Comment by jeroen** [comment]
@drnurul please include your system info and example code if you want any help.
