### ISSUE TITLE
curl package uses an undefined symbol from libcurl

### ISSUE THREAD

**Issue by brook-milligan** [jeroen/curl#207]
It seems that the curl package tries to use a symbol (_curl_is_long_option) from libcurl that is not defined in the library.  Consequently, the installation fails.  The following is a transcript of a portion of the build.

** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for 'curl' in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/scratch/www/R-curl/work/.destdir/usr/pkg/lib/R/library/curl/libs/curl.so':
 /scratch/www/R-curl/work/.destdir/usr/pkg/lib/R/library/curl/libs/curl.so: Undefined PLT symbol "_curl_is_long_option" (symnum = 56)
Error: loading failed
Execution halted
ERROR: loading failed

**Comment by jeroen** [comment]
Can you please tell me which version of curl you are installing and which operating system you use?

**Comment by brook-milligan** [comment]
> On Sep 27, 2019, at 7:50 AM, Jeroen Ooms <notifications@github.com> wrote:
> 
> Can you please tell me which version of curl you are installing and which operating system you use?

Sorry.

curl-7.66.0 on both NetBSD and MacOSX.

Cheers,
Brook

**Comment by jeroen** [comment]
We test with curl 7.66.0 on MacOS and I cannot reproduce your problem. Are you using the latest version (2.2) of the R package? Are you compiling with any special cflags?

Could it be that you have multiple versions of libcurl installed?
