### ISSUE TITLE
handle_getopt() functionality

### ISSUE THREAD

**Issue by nbenn** [jeroen/curl#210]
Is there a way to inspect the current state of a handle? Say i have an handle like

```
handle <- curl::new_handle(useragent = "my_app")
```

How could I later, given the handle, find out my `useragent` setting? Is this possible?

**Comment by nbenn** [comment]
I just came across this again, and realized that I opened this issue more than a year ago. Happy to close if this is not possible and if no one else finds this useful.

Maybe I can elaborate a bit on my use-case: In unit tests, using `testthtat::with_mock()`, I'd like to check whether the handle I'm passing to the mocked function has certain `opts` set. Does anyone have pointers on how to go about this?

**Comment by jeroen** [comment]
No, it's not possible to introspect the handle options. You can use `handle_data()` to see the response fields, or `curl_fetch_echo()` to perform a request to a local server.
