### ISSUE TITLE
Error of curl_fetch_memory with LDAP

### ISSUE THREAD

**Issue by eblondel** [jeroen/curl#211]
Hello @jeroen ,

I'm trying to query LDAP with ``curl_fetch_memory``  for a small LDAP R client i'm drafting [here](https://github.com/eblondel/ldap4R). For now, i've tried it with ``RCurl``, but I would like to avoid relying on it, and would prefer using ``curl`` instead.

I'm trying to reproduce ```RCurl:getURL("ldap://localhost:389")``` that works, with ``curl``:

```{r}
h <- new_handle()
curl_fetch_memory("ldap://localhost:389",h)
```
but I get an error: 

```{r}
Error in curl_fetch_memory("ldap://localhost:389", h) : 
  LDAP local: Mémoire insuffisante
```

To test this locally i'm using a test LDAP docker image available with : 
```
docker pull rroemhild/test-openldap
docker run --privileged -d -p 389:389 rroemhild/test-openldap
```

Thanks a lot if you can help figuring out what's wrong,

Best
Emmanuel

**Comment by jeroen** [comment]
Which OS do you get these errors? It seems to work on my MacOS:

```
cat(rawToChar(curl_fetch_memory("ldap://localhost:389")$content))
# DN:
# 	objectClass: top
# 	objectClass: OpenLDAProotDSE
#
```

**Comment by eblondel** [comment]
Locally, i work on Windows OS, where i get this error.

**Comment by jeroen** [comment]
This is caused by https://github.com/curl/curl/issues/4261

**Comment by eblondel** [comment]
Thanks @jeroen , but then why it's working with ``RCurl`` package? what's the "magic" (or hack) there?

**Comment by jeroen** [comment]
RCurl is using a very old verison of libcurl. The `curl` package uses a quite recent version of libcurl which generally works much better. However it seems that this is a recent bug, unfortunately.
