### ISSUE TITLE
Unable to use send_mail with SMTPS

### ISSUE THREAD

**Issue by jcheng5** [jeroen/curl#212]
SMTP connections can be encrypted either using TLS at the connection level (smtps://hostname:465), or, STARTTLS at the protocol level (smtp://hostname:587). The current implementation of `send_mail` only supports smtp://, not smtps://, so TLS cannot be used.

I'm submitting a PR that allows for the explicit specification of the protocol, and also clarifies that the `use_ssl` parameter controls STARTTLS, not connection-level TLS.

As a side note, you might consider changing the default value of `use_ssl` to `TRUE`; I can't think of why you wouldn't want STARTTLS.

**Comment by jcheng5** [comment]
FYI, @rich-iannone and I are currently trying to release a package that needs this functionality. Unless you have an objection, we were planning to copy the `send_mail` function into our package for now; we'd remove it if and when the CRAN version of curl implements smtps://.

**Comment by jeroen** [comment]
> FYI, @rich-iannone and I are currently trying to release a package that needs this functionality. Unless you have an objection, we were planning to copy the send_mail function into our package for now; we'd remove it if and when the CRAN version of curl implements smtps://.

Of course, to for it :) And thanks for still fixing things here as well.
