### ISSUE TITLE
SNI or certificate check failed in send_mail after updating from v4.1 to v 4.3

### ISSUE THREAD

**Issue by mkoohafkan** [jeroen/curl#215]
I recently updated from `curl` package version `4.1` to `4.3` and am no longer able use the `send_mail` function. I now get the error:

> Error in curl_fetch_memory(smtp_server, handle = h) : 
  schannel: SNI or certificate check failed: SEC_E_WRONG_PRINCIPAL (0x80090322) - The target principal name is incorrect.

I have verified that this error occurs only after updating from version `4.1` to `4.3` (didn't test `4.2`). 

I have tried specifying my own security certificate using the `cainfo` argument (which works with `curl_fetch_memory` for other systems in my organization that require the certificate) and tried specifying the argument `use_ssl = "no"`.

Is this a bug, or did the update introduce new requirements for `send_mail`?

**Comment by jeroen** [comment]
One thing that has changed is that the `use_ssl` parameter is enabled by default. Can you try setting `use_ssl` to `"no"` or `FALSE`?

**Comment by mkoohafkan** [comment]
Yes, I have already tried that but no success. I have also tried all combinations of `smtp://` vs `smtps://`, `cainfo`, `use_sll = TRUE/FALSE` and `ssl_verifypeer = FALSE`. If I specify the host with `smtps://` I invariably get a timeout error, otherwise I get the SNI error.

- use "smtp://my.host" and `use_ssl = FALSE`
> Error in curl_fetch_memory(smtp_server, handle = h) : 
  schannel: SNI or certificate check failed: SEC_E_WRONG_PRINCIPAL (0x80090322) - The target principal name is incorrect.

- use "smtps://my.host" and `use_ssl = "no"`
> Error in curl_fetch_memory(smtp_server, handle = h) : 
  Timeout was reached: [my.host] Connection timed out after 10000 milliseconds

**Comment by mkoohafkan** [comment]
Oh No, sorry---Problem In Chair, Not In Code! My code sends two messages, and I was only setting the option in the second one.
