### ISSUE TITLE
Vectorise curl_download

### ISSUE THREAD

**Issue by hadley** [jeroen/curl#222]
Because TIL that `download.file` is, and you could do some nice parallel downloading by default.

**Comment by jeroen** [comment]
There's an [existing request](https://github.com/jeroen/curl/issues/166) for this, but my main concern is how to generalize error handling.

The `curl_download()` function, like `download.file()`, errors on an http-error (e.g. 404). So for the caller, there are only two outcomes to consider:

  - The function succeeds, it is safe to assume the file is there (and may need to be cleaned)
  - The function errors, there is no file downloaded.

However if you vectorize this, it can happen that some transfers succeed and some fail. Even worse if it gets interrupted, some transfers may be completed, some failed, and some in progress.

How would you expect this to behave?

**Comment by gaborcsardi** [comment]
Take a vector of URLs and a vector of destination files. Return a list of the same length. If a download has finished, then include the destination path there. If it failed, include an error object. If it was interrupted, then include the interrupt object there.

Have a "check" function that makes sure that all downloads were ok.

I realize that the return value is a breaking change, so you might want to have this as a new function, e.g. `curl_downloads()`.

**Comment by jeroen** [comment]
Your proposal would mean that the function no longer raises an error in the scenario of a single file, which fails to download?

**Comment by gaborcsardi** [comment]
Yes, that's another reason I suggested creating a new function.

**Comment by gaborcsardi** [comment]
You could also have an option whether it should fail early, but that can be added later.

**Comment by hadley** [comment]
`curl_downloads()` would be an obvious name.

**Comment by jeroen** [comment]
How would you want to specify the input request? In `curl_download()` we take a `handle` which can be configured with request options/headers. Should the user provide a list of options that we use for each request?

**Comment by gaborcsardi** [comment]
I don't think it is super important to take handles for the first implementation. But certainly you could accept a list of handles and urls, mixed? Or probably is is more idiomatic in curl to have a separate `handles` argument, a list of handles of the same length. This would default to `NULL`, meaning a list of new handles?

**Comment by jeroen** [comment]
I added a `multi_download` function, would really appreciate your feedback!

**Comment by gaborcsardi** [comment]
Based on a quick look only, the API looks pretty good to me!
