### ISSUE TITLE
Use curl installed from homebrew

### ISSUE THREAD

**Issue by caldwellst** [jeroen/curl#225]
The GitHub README recommends the following, but I get the following warning and it doesn't seem to work:
```zsh
brew link --force curl
#>Warning: Refusing to link macOS provided/shadowed software: curl
#>If you need to have curl first in your PATH run:
#>  echo 'export PATH="/usr/local/opt/curl/bin:$PATH"' >> ~/.zshrc
```
This works fine within the terminal, so `curl --version` gives 7.70.0. I've setup my .Rprofile with:
```r
Sys.setenv(PATH = paste("/usr/local/opt/curl/bin", Sys.getenv("PATH"), sep=":"))
```
And my PATH variable is properly setup.
```r
Sys.getenv("PATH")
#>"/usr/local/opt/curl/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/RStudio.app/Contents/MacOS/postback"
```
Yet, when I try to re-install curl from source, it still is accessing the macOS libcurl version
```r
curl::curl_version()
#>$version
#>[1] "7.64.1"
```
Have I misunderstood instructions from the README or is there an alternative method to get the package to source from the brew installed curl?

**Comment by jeroen** [comment]
Sorry that information is outdated. Let me update it.

**Comment by jeroen** [comment]
OK fixed now.
