### ISSUE TITLE
Bug in curl_escape

### ISSUE THREAD

**Issue by jeroen** [jeroen/curl#228]
`curl::curl_escape("")`

**Comment by sckott** [comment]
just ran into this as well

**Comment by jeroen** [comment]
Which version of libcurl?

**Comment by sckott** [comment]
libcurl 7.71.0

**Comment by jeroen** [comment]
Strangely, I am not getting this error anymore with `libcurl 7.71.0`. Can you try reinstalling the curl package?

**Comment by sckott** [comment]
from source i assume?

**Comment by sckott** [comment]
i think this https://github.com/ropensci/rbhl/issues/28#issuecomment-638398244 was the last time I installed curl - If I install from cran binary or cran from source I don't get the error and the curl version is `7.64.1`, same as `curl --version`

**Comment by sckott** [comment]
Ugh, there's a number of APIs my pkgs work with that still have [that cert issue](https://github.com/ropensci/rbhl/issues/28)   - so tests are failing with curl `7.64.1`, but if I switch to curl `7.71.0`, then I get segfaults if i somehow am passing am empty string to `curl_escape` - I guess for now I use `7.64.1` and filter out any tests that interact with APIs that have the cert issue

**Comment by jeroen** [comment]
I think the segfault is a local problem. Doesn't it get solved if you reinstall the curl package?

**Comment by sckott** [comment]
yes, but then I have the cert issue. Anyway, will just wait until the various certs are fixed
