### ISSUE TITLE
curl_download URL encoding

### ISSUE THREAD

**Issue by ben-schwen** [jeroen/curl#233]
As also mentioned [here](https://github.com/Rdatatable/data.table/issues/4659) it seems that `curl_download` has a problem with url encoding of spaces etc.

```
library(curl)
url = "https://github.com/OpportunityInsights/EconomicTracker/raw/main/data/Google Mobility - County - Daily.csv"
tmpfile = tempfile()

# fails with HTTP error 400
curl_download(url, tmpfile)

# works
curl_download(utils::URLencode(url), tmpfile)

print(url)
print(utils::URLencode(url))
```

**Comment by andodet** [comment]
Having the exact same problem, passing a url before encoding it leads to a 400 error. 
@jeroen should `utils::URLencode()` to correctly escape spaces before calling `R_download_curl`?

**Comment by jeroen** [comment]
Yes, spaces in a URL can either be replaced with `+` or wrapped in `curl_escape()` or `utils::URLencode()`. We cannot do this automatically because usually the URL is already escaped and then it leads to double escaping if we do it again.
