### ISSUE TITLE
How do I setup the grant_type parameter using the curl package in R?

### ISSUE THREAD

**Issue by syntheso** [jeroen/curl#234]
I am trying to implement grant_type=client_credentials in my curl request from R but can't find out how to do this properly. This request would use the -d flag, so I think that is the body of the request.

How do I set this up here in curl? I can't find an example. For now, I use a "body" tag, but this brings the following error:

> Authentication failed due to invalid authentication credentials or a missing Authorization header.

   ```
 library(curl)
    
    
    # get access token
    h <- new_handle()
    
    handle_setheaders(h, 
                      "Accept" = "application/json",
                      "Accept-Language" = "en",
                      "body" = "grant_type=client_credentials"
                      )
    
    
    handle_setopt(h,
                  userpwd = "username:password"
                  )
```

This is the curl request I am trying to replicate in R (which I can confirm works in Terminal):

```
curl -v https://api.blah.com \
   -H "Accept: application/json" \
   -H "Accept-Language: en_US" \
   -u "username:password" \
   -d "grant_type=client_credentials"

```

**Comment by syntheso** [comment]
Seems like this is a replication of #115 which went unanswered.

**Comment by jeroen** [comment]
Looks like you're posting a form? See the vignette: https://cran.r-project.org/web/packages/curl/vignettes/intro.html#posting_forms

**Comment by syntheso** [comment]
Hi, yes I already tried that actually. I get the same error as above. Code:

```
# get access token
h <- curl::new_handle(verbose = TRUE)


curl::handle_setopt(h,
                    copypostfields = "grant_type=client_credentials",
                    userpwd = "username:oassword"
)


curl::handle_setheaders(h, 
                  "Accept" = "application/json",
                  "Accept-Language" = "en_US"
                  )


req <- curl_fetch_memory("https://api.blah.com", handle = h)

```

**Comment by syntheso** [comment]
And yes, the equivalent pipe operation raises the same error:

```
new_handle() %>%
  handle_setopt(copypostfields = "grant_type=client_credentials", userpwd = "username:password") %>%
  handle_setheaders("Accept" = "application/json", "Accept-Language" = "en_US") %>%
  curl_fetch_memory(url = "https://api.url.com") %$% content %>% 
  rawToChar %>% jsonlite::prettify()

```

And to reconfirm, the curl command as in my first post does not return the error.

**Comment by jeroen** [comment]
I can't debug this without output or url, but if you add `verbose=TRUE` to the handle options, perhaps you can see how it is different from the command line

**Comment by jeroen** [comment]
Can you also try adding `httpauth = 1L` to your handle options? That forces authentication, even if the server doens't ask for it.

**Comment by syntheso** [comment]
> Can you also try adding `httpauth = 1L` to your handle options? That forces authentication, even if the server doens't ask for it.

Aha, this works now! Thank you!
