### ISSUE TITLE
Provide interface to curl_easy_getinfo

### ISSUE THREAD

**Issue by hadley** [jeroen/curl#246]
In particular, I'd like to get `CURLINFO_PROTOCOL`, `CURLINFO_HTTP_VERSION`, and `CURLINFO_EFFECTIVE_METHOD` so that given a response from curl I can closely simulate what the HTTP message would've looked like (which I think is useful for learning). Alternatively, it might be easier to just add these to `handle_data()`.

**Comment by jeroen** [comment]
Yes we could add these fields to `handle_data()`. Note that these are all recent additions to libcurl, see the manual pages for the libcurl version when they became available. In particular `CURLINFO_EFFECTIVE_METHOD` is not yet available on most systems.
