### ISSUE TITLE
Optionally preserve case of headers

### ISSUE THREAD

**Issue by hadley** [jeroen/curl#247]
Again, nice to have original case to present to users exactly what the server sent (even though it doesn't matter because headers are case sensitive).

**Comment by jeroen** [comment]
You mean in the `curl::parse_headers_list` function?

**Comment by hadley** [comment]
Yeah, maybe I should just provide my own version of that function.

**Comment by hadley** [comment]
After doing that I realised that you are right and the server is sending all in lower case. Doh.

**Comment by hadley** [comment]
Ok, but it's not every server, just httpbin and google, so preserving case is still worth it for httr2 (but not for curl, which is why I closed this issue)
