### ISSUE TITLE
CRAN Note non-API call to R

### ISSUE THREAD

**Issue by rfhb** [jeroen/curl#251]
Hi and many thanks for the R package curl! CRAN's check results page reports since about two days an error for r-devel-windows-x86_64-gcc10-UCRT and notes for all other platforms, see https://cran.r-project.org/web/checks/check_results_curl.html:  

```
File 'curl/libs/curl.so':
     Found non-API call to R: 'R_new_custom_connection'
    Compiled code should not call non-API entry points in R.
```

Am opening this issue just to flag these check results in view of the potential impact downstream, just in case not yet known.

**Comment by jeroen** [comment]
Yes I know. These things are unrelated to each other.
