### ISSUE TITLE
Package Fails to Compile From Source on Windows

### ISSUE THREAD

**Issue by ArcadeAntics** [jeroen/curl#252]
When I try to install 'curl' from source, it comes with the following error
![image](https://user-images.githubusercontent.com/14181583/123195348-0597dc80-d476-11eb-9870-89ef7f6798f8.png)
which claims that it cannot find function 'download.file'. I have my 'Rscript' set so that only base is attached upon starting a new R session (that is, RSCRIPT_DEFAULT_PACKAGES=NULL). This could be fixed by changing 'download.file' to 'utils::download.file' (and same with 'unzip', change to 'utils::unzip'). Thank you!

**Comment by jeroen** [comment]
Just don't set `RSCRIPT_DEFAULT_PACKAGES` if you want packages to work as expected...

**Comment by ArcadeAntics** [comment]
terrible solution and 3 years too late
