### ISSUE TITLE
How does {curl} support AD

### ISSUE THREAD

**Issue by robertdj** [jeroen/curl#253]
Hi

Thanks for a great package! I wonder if you can help me understand how {curl} supports Active Directory authentication? 

With the command line `curl` I use the `--negotiate` flag to authenticate and the `-u :` flag to use my Kerberos/Windows user credentials:
```
curl --ntlm -u : --negotiate <url>
```

I'm not sure where to start looking at the `.Call`s in the code to understand how {curl} supports the same behavior. Can you help me out?

**Comment by jeroen** [comment]
The curl R package interfaces with the libcurl C library, not the command line tool. You probably need to set some options, see `curl_options()` for the list of supported options.

Also see: https://cran.r-project.org/web/packages/curl/vignettes/intro.html#Setting_handle_options

**Comment by robertdj** [comment]
Thanks, I'll take a look at the options.
