### ISSUE TITLE
Usage of has_internet in special setups

### ISSUE THREAD

**Issue by romunov** [jeroen/curl#254]
Imagine a setup where DNS resolving is enabled but access to the internet is cut off. In this case, `has_internet` would return `TRUE` ([here](https://github.com/jeroen/curl/blob/0d355776269b703824cd81efef52b4400e3397ca/R/nslookup.R#L47)).

Is this considered a too edge-casey, or could we also think about accessing the internet for an end-to-end test?

**Comment by jeroen** [comment]
I think this will make the test too slow, and indeed it seems like of a weird edge case because you obviously need an internet connection to perform a DNS request. I guess you're saying you have internet connection but your firewall blocks http?
