### ISSUE TITLE
curl_fetch_memory server certificate verification failed

### ISSUE THREAD

**Issue by ewenharrison** [jeroen/curl#261]
Hi,

Many thanks for any help with this issue, apologies for disturbing. I have very little understanding of curl!

I'm on Ubuntu 20.04 and getting the following error:

```
> curl::curl_fetch_memory("https://crandb.r-pkg.org/finalfit/all")
Error in curl::curl_fetch_memory("https://crandb.r-pkg.org/finalfit/all") : 
  server certificate verification failed. CAfile: none CRLfile: none
```

It is similar to this issue https://github.com/jeroen/curl/issues/259 and this:
https://unix.stackexchange.com/questions/676528/server-certificate-verification-failed-cafile-etc-ssl-certs-ca-certificates-c
The solution didn't solve the problem. 

If a use curl::curl I get this:
```
> curl::curl("https://crandb.r-pkg.org/finalfit/all")
A connection with                                                   
description "https://crandb.r-pkg.org/finalfit/all"
class       "curl"                                 
mode        "r"                                    
text        "text"                                 
opened      "closed"                               
can read    "yes"                                  
can write   "no" 
```

If I run curl from the command line I get the expected return. I'm not understanding why I can access the site from the command line but not `curl::curl_fetch_memory` if it is a system certificate error. 

```
curl https://crandb.r-pkg.org/finalfit/all
{"_id":"finalfit","_rev":"24-dc97d1f0177f884928fcaa5d22e5e9c8","name":"finalfit","archived":false,"versions":{"0.7.8":{"Pac
etc.
```

I've gone through all of the certificate updating procedures, e.g. 
https://stackoverflow.com/questions/21181231/server-certificate-verification-failed-cafile-etc-ssl-certs-ca-certificates-c

The root certificate of the site in question (ISRG Root X1 certificate) is definitely in my certificate list via `sudo dpkg-reconfigure ca-certificates`. 

I've seen issues with LetsEncrypt certificates, could that be an issue? e.g.
https://stackoverflow.com/questions/69394684/is-git-broken-on-ubuntu-20-04-by-the-30-sept-letsencrypt-certificate-expiry

Many thanks for any help!
Best wishes,
Ewen

refs
https://github.com/metacran/metacranweb/issues/115
https://github.com/r-lib/pkgdown/issues/1976

**Comment by jeroen** [comment]
What is your `curl::curl_version()` ? And can you try adding verbose=T to get some more output:

```r
library(curl)
h <- new_handle(verbose=TRUE)
req <- curl::curl_fetch_memory("https://crandb.r-pkg.org/finalfit/all", handle = h)
```

**Comment by ewenharrison** [comment]
Thanks so much for your help, it is greatly appreciated. 

```
> curl::curl_version()
$version
[1] "7.68.0"

$ssl_version
[1] "GnuTLS/3.6.13"

$libz_version
[1] "1.2.11"

$libssh_version
[1] "libssh/0.9.3/openssl/zlib"

$libidn_version
[1] "2.2.0"

$host
[1] "x86_64-pc-linux-gnu"

$protocols
 [1] "dict"   "file"   "ftp"    "ftps"   "gopher" "http"   "https"  "imap"   "imaps"  "ldap"   "ldaps"  "pop3"   "pop3s"  "rtmp"   "rtsp"   "scp"   
[17] "sftp"   "smb"    "smbs"   "smtp"   "smtps"  "telnet" "tftp"  

$ipv6
[1] TRUE

$http2
[1] TRUE

$idn
[1] TRUE

Warning message:
In for (i in seq_along(args)) { :
  closing unused connection 4 (https://crandb.r-pkg.org/finalfit/all)
```

```
> library(curl)
Using libcurl 7.68.0 with GnuTLS/3.6.13
> h <- new_handle(verbose=TRUE)
> req <- curl::curl_fetch_memory("https://crandb.r-pkg.org/finalfit/all", handle = h)
* Hostname in DNS cache was stale, zapped
*   Trying 107.170.56.25:443...
* TCP_NODELAY set
* Connected to crandb.r-pkg.org (107.170.56.25) port 443 (#16)
* found 1015 certificates in /etc/ssl/certs
* ALPN, offering h2
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* server certificate verification failed. CAfile: none CRLfile: none
* Closing connection 16
Error in curl::curl_fetch_memory("https://crandb.r-pkg.org/finalfit/all",  : 
  server certificate verification failed. CAfile: none CRLfile: none
```

**Comment by gaborcsardi** [comment]
```
* server certificate verification failed. CAfile: none CRLfile: none
```

This probably means that you don't have any certificates? Do you have the `ca-certificates` package installed? 
Can you access other HTTPS websites?

FWIW usually we use OpenSSL with libcurl on Ubuntu, and not GnuTLS, because OpenSSL works better in general. I.e. we compile curl with the `libcurl4-openssl-dev` Ubuntu package and not `libcurl4-gnutls-dev`.

**Comment by ewenharrison** [comment]
Thanks. Yes, all certificates are installed and have been reinstalled. The certificate in question is present. I haven't found any other https sites I can't access. The site in question is accessible from the command line. 
The issue is from the package pkgdown, rather than a general problem I'm trying to solve. 
https://github.com/r-lib/pkgdown/blob/dcec859cab08ff8852f5ee5ab09f3f57ec038805/R/build-news.R#L253
Many thanks again for your help and interest.

**Comment by gaborcsardi** [comment]
So just to make sure, does this work?
```
h <- new_handle(verbose=TRUE)
req <- curl::curl_fetch_memory("https://miktex.org/", handle = h)
```

**Comment by jeroen** [comment]
You have compiled the curl package against gnutls instead of openssl. Can you try rebuilding it with openssl? Do:

```
sudo apt-get install libcurl4-openssl-dev
```
and then reinstall the curl package in R: `install.packages('curl')`

**Comment by ewenharrison** [comment]
```
> h <- new_handle(verbose=TRUE)
> req <- curl::curl_fetch_memory("https://miktex.org/", handle = h)
* Found bundle for host miktex.org: 0x5575c1214c70 [can multiplex]
* Re-using existing connection! (#24) with host miktex.org
* Connected to miktex.org (5.175.24.104) port 443 (#24)
* Using Stream ID: 3 (easy handle 0x5575c2eb1540)
> GET / HTTP/2
Host: miktex.org
user-agent: RStudio Server Pro (1.4.1717.3); R (4.1.1 x86_64-pc-linux-gnu x86_64 linux-gnu)
accept: */*
accept-encoding: deflate, gzip, br

< HTTP/2 200 
< content-type: text/html; charset=utf-8
< server: Microsoft-IIS/10.0
< strict-transport-security: max-age=2592000
< date: Thu, 23 Dec 2021 10:08:17 GMT
< 
* 118 data bytes written
* Connection #24 to host miktex.org left intact
```
For the first one. 
Will re-install.

**Comment by ewenharrison** [comment]
Solved with this https://github.com/jeroen/curl/issues/261#issuecomment-1000188925 !
Many thanks again for your help, it is greatly appreciated.

**Comment by AlexandrProv** [comment]
Hello, I encountered two similar errors. I tested on two laptops with the Alt Linux system. The error did not appear on all URLs. Sharing solutions:

For example, I took the same URL: https://crandb.r-pkg.org/finalfit/all

1. In the first case, I saved the certificate to a file and specified the path to it in the request parameter "cainfo".

`curl::curl_fetch_memory("https://crandb.r-pkg.org/finalfit/all" )`

Error:
![ssl_cert](https://github.com/jeroen/curl/assets/101949219/141e738f-eeb5-4b36-9201-acf941dbcc6e)

SSL peer certificate or SSH remote key was not OK: [crandb.r-pkg.org] SSL certificate problem: unable to get local issuer certificate

Solution:

Bash:
`openssl s_client -showcerts -servername crandb.r-pkg.org -connect crandb.r-pkg.org:443 > cran_cert.pem`

R:
`h <- new_handle()
handle_setopt(h, cainfo = "/home/user/cran_cacert.pem")
curl::curl_fetch_memory("https://crandb.r-pkg.org/finalfit/all", handle = h)`

**Comment by AlexandrProv** [comment]
2. In the second case, it was a matter of the HTTP2 version. I switched to another version CURL_HTTP_VERSION_1_1:

`curl::curl_fetch_memory("https://crandb.r-pkg.org/finalfit/all" )`

![writing_error](https://github.com/jeroen/curl/assets/101949219/9ee295bf-6e7d-4e0d-abc7-e5f4ea4ec049)

Error:
Failed writing received data to disk/application

Solution:
`h <- new_handle()
handle_setopt(h, http_version = 2)
curl::curl_fetch_memory("https://crandb.r-pkg.org/finalfit/all", handle = h)`

**Comment by jeroen** [comment]
> Error:
> Failed writing received data to disk/application

This is a bug in the latest libcurl release 8.7.1, see: https://github.com/curl/curl/issues/13493
It should be fixed when your linux distro updates libcurl.

**Comment by AlexandrProv** [comment]
> > Ошибка: 
> > не удалось записать полученные данные на диск/приложение.
> 
> Это ошибка в последней версии libcurl 8.7.1, см.: [curl/curl#13493.](https://github.com/curl/curl/issues/13493) Ее следует исправить, когда ваш дистрибутив Linux обновит libcurl.

Understood, thank you for the response.
