### ISSUE TITLE
No HTTP2 support in windows environment? 

### ISSUE THREAD

**Issue by hrylx** [jeroen/curl#262]
Hi, 

is it somehow possible to enable http2 support in a windows environment? Or generelly use an other curl version to build the package from source? Or maybe build R from Source with newer Curl included?

I develop my scripts in windows and later transfer them to my server which is running ubuntu (and where curl 7.81 with http2 is recognized and running perfectly smooth).

problem: some server responses do work in ubuntu, but don´t work in windows, which often makes debugging a hard task...

**Comment by brunomioto** [comment]
+1

**Comment by hrylx** [comment]
Hi,
On Windows we are still stuck on almost 4 year old version 7.64.1 of (lib)curl, without support for HTTP2/3 and smb.
Any chance to update the package for Windows?

**Comment by jeroen** [comment]
The latest github version now has libcurl 7.84.0 + nghttp2

**Comment by hrylx** [comment]
Thank you very much, that helps a lot!
