### ISSUE TITLE
Expose curl's url parsing

### ISSUE THREAD

**Issue by hadley** [jeroen/curl#266]
By calling `curl_url()`, then `curl_url_set()`, then retrieving the components with `curl_url_get()`.

**Comment by jeroen** [comment]
We could do it but a problem is that this API was introduced relatively recently, in libcurl 7.62.0. So we would need a fallback for older linux systems, including ubuntu-18.04 (which is the CI default): https://packages.ubuntu.com/bionic/libcurl4-openssl-dev

**Comment by hadley** [comment]
Ah darn it 😞

**Comment by jeroen** [comment]
Sadly the version of libcurl in RHEL-8 is also too old :/ But we coudl do it and provide a fallback.

**Comment by jeroen** [comment]
Yeah it's really unfortunate, I also would like to use the new symbols API but this requires libcurl 7.73 irc.

**Comment by hadley** [comment]
Would it be possible to vendor in the url parsing code for older libcurl? Or is it too entangled with the rest of the code base?

**Comment by jeroen** [comment]
It is pretty entangled, importing lots of the internal libcurl headers: https://github.com/curl/curl/blob/HEAD/lib/urlapi.c#L848

**Comment by jeroen** [comment]
I am now leaning towards bundling [ada](https://github.com/ada-url/ada) as a fallback for older systems. It seems pretty fast and robust. There is also an R package interfacing this parser but given that it is just a single c++ file, it will be easy to bundle.

**Comment by jeroen** [comment]
This is now implemented in the dev branch, see https://jeroen.r-universe.dev/curl

**Comment by jeroen** [comment]
This has landed on CRAN in curl 6.0.0
