### ISSUE TITLE
Can't get response

### ISSUE THREAD

**Issue by jba31** [jeroen/curl#277]
Hi,
We have a problem with curl fetch functions.
We can't get data from our url with curl_fetch_disk or curl_fetch_memory (same issue)
The server response contains \n after header response. The problem isn't the header request.
We use last curl version 4.3.2

Code
```
h <- curl::new_handle()
curl::handle_setopt(h, copypostfields = '{"request_parameters": {}}'        )
y <- curl::curl_fetch_disk(path="./<myfile>","http://<server>/<myurl>/", handle = h
)
```

Error
```
Error in curl::curl_fetch_disk(destfile = path="./<myfile>","http://<server>/<myurl>/",  : 
  Failed writing received data to disk/application
```

Content in myfile
```
count

```

Response from server
```
count
1323558

```

thanks in advance

**Comment by jeroen** [comment]
Can you try to make an example that is reproducible for me, using a public url? Otherwise it is impossible for me to help you.
