### ISSUE TITLE
Error in curl when trying get data from gbif

### ISSUE THREAD

**Issue by feliperossetto** [jeroen/curl#279]
Dear all,

I am using the R package rgbif and plyr to get occurrences data of a species, but when I run the command:

spp <- occ_search(scientificName = "Pisonia aculeata")

 the resulting message was "Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_CERT_EXPIRED (0x80090328) '' in which the certificate expired.

I was searching other similar issues here and followed a similar path where it was necessary to install a recent version of the package curl, but the problem persists. I am using an old version of windows (windows 7), but I don't think this could be the problem.

I am grateful in advance and I can provide more details too.

Thank you very much,
Felipe

**Comment by jay** [comment]
If your computer is set to the correct date then the certificate probably is expired. Try using a browser to access the URL.
