### ISSUE TITLE
Request to Implement Alternate File Upload Name

### ISSUE THREAD

**Issue by the-mad-statter** [jeroen/curl#289]
I would like to be able to perform the following (working) command line curl command using {curl} as the specific API I am uploading to does not otherwise support specifying a new filename:

```
CURL=`which curl`
$CURL -H "Accept: application/json" \
      -F "token=TOKEN_TOKEN" \
      -F "content=file" \
      -F "action=import" \
      -F "record=1" \
      -F "field=file_upload" \
      -F "file=@old.txt;filename=new.txt" \
      https://somewhere.com/api/
```

I suspect this means somehow implementing [curl_mime_filename](https://curl.se/libcurl/c/curl_mime_filename.html) which I do not think is currently supported.

If this is not of interest, any tips or pointers on how I might add this would be appreciated.

**Comment by jeroen** [comment]
We should probably combine this with porting the [form.c](https://github.com/jeroen/curl/blob/master/src/form.c) implementation to the new [curl_mime](https://curl.se/libcurl/c/curl_mime_init.html) API. Right now we are still using the legacy form API.

**Comment by the-mad-statter** [comment]
I figured out the old API was still being used when I started investigating how I might implement this myself. I am working on a solution using the old API for now and can submit a pull request if I get it working and that is of interest. I would commit to helping port form.c, but I don't know how fast I would get that done.

**Comment by jeroen** [comment]
It's not difficult but just a little messy if we want to support this for all cases in the old API.

Basically we need to add a [CURLFORM_FILENAME](https://curl.se/libcurl/c/curl_formadd.html#CURLFORM_FILENAME) flag to the relevant cases in [form.c](https://github.com/jeroen/curl/blob/master/src/form.c). But this legacy API makes it very difficult to set this flag conditionally.

**Comment by jeroen** [comment]
Actually what you want can already be accomplished, simply by giving your file the correct name when you upload it?

Is there any reason your local file has to be called `old.txt` ? Maybe you can just rename or symlink it to `new.txt` and then upload it?

**Comment by the-mad-statter** [comment]
The reason this issue came up is the I intend to run my code on Windows which does not allow some characters in file names such as colons. Therefore, I cannot just rename the file when uploading. [Here](https://github.com/jeroen/curl/compare/master...the-mad-statter:curl:master) is what I came up with. I think the if-else cases can be simplified by modifying `curl::form_file()` to include the alternate filename in the third position with a default of `basename(path)` and then reordering the elements to match what the C code expects.

**Comment by jeroen** [comment]
I think your solution crashes if a users sets `name = NULL` ?

**Comment by the-mad-statter** [comment]
ok - let me add some more if-elseing to protect against that

**Comment by the-mad-statter** [comment]
Will [this](https://github.com/jeroen/curl/compare/master...the-mad-statter:curl:master) suffice for a PR?

**Comment by jeroen** [comment]
Yeah I think that works. It's a lot of if-else but I guess there is no better way with the API. It will probably get easier when we port it to the new api.

**Comment by jeroen** [comment]
This was merged in https://github.com/jeroen/curl/pull/290
