### ISSUE TITLE
Help making a curl request to a server that only accepts TLS 1.2?

### ISSUE THREAD

**Issue by tomcardoso** [jeroen/curl#291]
Hi there,

This isn't really a bug or issue, per se, but I've struggled all day to figure out the correct syntax for this. I'm trying to do a `curl_fetch_memory` request inside a GitHub Actions process, like so:
```r
curl_fetch_memory('https://www.ourcommons.ca/DocumentViewer/en/44-1/house/sitting-1/journals')
```

But that returns this error:
```
*   Trying 204.101.151.48:443...
* Connected to www.ourcommons.ca (204.101.151.48) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* OpenSSL SSL_connect: Connection reset by peer in connection to www.ourcommons.ca:443
* Closing connection 0
Attempt to run script /home/runner/work/run.R failed. Error message: Error in curl_fetch_memory(.data$journal_url): OpenSSL SSL_connect: Connection reset by peer in connection to www.ourcommons.ca:443
```

The GitHub Action uses the `ubuntu-22.04` image, and runs R `4.0.4`. Here's the `curl_version()` output from the GitHub Action:
```
version: 7.81.0
ssl_version: OpenSSL/3.0.2
libz_version: 1.2.11
libssh_version: libssh/0.9.6/openssl/zlib
libidn_version: 2.3.2
host: x86_64-pc-linux-gnu
protocols: dict, file, ftp, ftps, gopher, gophers, http, https, imap, imaps, ldap, ldaps, mqtt, pop3, pop3s, rtmp, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
ipv6: TRUE
http2: TRUE
idn: TRUE
```

After some research, I discovered that ourcommons.ca seems to only accept TLS 1.0,. 1.1 and 1.2, per https://www.ssllabs.com/ssltest/analyze.html?d=www.ourcommons.ca&s=204.101.151.48. 

I thought I could configure a handler like so, but it hasn't worked:
```r
h <- new_handle(verbose = TRUE, sslversion = 6L)
curl_fetch_memory('https://www.ourcommons.ca/DocumentViewer/en/44-1/house/sitting-1/journals', handle = h)
```

Could you help me debug this? The request works locally out-of-the-box and just defaults to TLS 1.2, but there's something about the GitHub Action environment that seems less permissive and I can't for the life of me figure it out. All my searches for GitHub Action-related `curl` or `openssl` issues come up empty.

**Comment by jeroen** [comment]
Just tried it on ubuntu 22.04 but it seems to work now. I'm guessing there was a server problem.
