### ISSUE TITLE
Pass an ID value through curl_fetch_multi / multi_run

### ISSUE THREAD

**Issue by mem48** [jeroen/curl#293]
I'm using `curl_fetch_multi` / `multi_run` to make lots of asynchronous requests

```
urls # character vector of urls to process

# Success Function
success <- function(res){
    data <<- c(data, rawToChar(res$content))
}
# Fail Function
failure <- function(msg){
    cat("Error: ", msg, "\n")
}

# Setup
pool <- curl::new_pool(host_con = 10)
data <- list()
for(i in seq_len(length(urls))){
    h <- curl::new_handle()
    curl::curl_fetch_multi(urls[i],
                           done = success,
                           fail = failure ,
                           pool = pool,
                           handle = h)
}
curl::multi_run(timeout = Inf, pool = pool)
```

This works, but the results don't always come back in the order they are sent. Is there a way to parse and ID value to `multi_run` so that I can sort the `data` list into the same order as the original `urls`

**Comment by mem48** [comment]
Thanks for the quick response. I implemented the example but I don't see how to retrieve the ID. Is there an additional step?

**Comment by mem48** [comment]
I thought I worked it out by adding:

```
handles <- list()
```
```
otp_success <- function(res){
    data <<- c(data, list(rawToChar(res$content)))
    handles <<- c(handles, curl::handle_data(h)$url)
  }
```
 But that just returns the last url over and over

**Comment by mem48** [comment]
Got it to work

```
urls2 <- list()
```

```
success <- function(res){
    data <<- c(data, list(rawToChar(res$content)))
    urls2 <<- c(urls2, res$url)
  }
```

```
data <- data[match(urls, urls2)]
```

**Comment by jeroen** [comment]
The trick of closures is that you don't define a single `success` callback like you do, but instead you redefine `success` for every handle, with a unique scope. Then you can pre-define an `i` or anything else in the unique scope of that callback.

Here is a minimal example. Note that each version of the `success ` has it's own `i` predefined:

```r
# Some random urls
pkgs <- c('jsonlite', 'ggplot2', 'dplyr', 'Rcpp', 'jose', 'tidyverse')
urls <- sprintf('https://cloud.r-project.org/web/packages/%s/DESCRIPTION', pkgs)

# Assign output in same order as input
out <- vector('list', length(urls))
pool <- new_pool()
lapply( seq_along(urls), function(i){
  h <- curl::new_handle()
  success <- function(res){
    out[[i]] <<- res
  }
  curl::curl_fetch_multi(urls[i], done = success, pool = pool, handle = h)  
})
curl::multi_run(pool = pool)
```

If you run this, you will see that the order of `out` matches the input order of urls.
