### ISSUE TITLE
CERT_TRUST_IS_NOT_TIME_VALID

### ISSUE THREAD

**Issue by DoctorTrilobite** [jeroen/curl#294]
Hello,

I am trying to pull data from TreeBASE:

install.packages("treebase")
library("treebase")

search_treebase(17613, by = "id.study")

I keep getting the following error and am not really getting anywhere reading fixes on sites.  From reading, this seems like an accessing certificate issue related to Windows (and not being time valid?) but I am still rather lost on how to fix this and to be honest exactly what it means. Also, I am somewhat new to R. The error I get is:

http://purl.org/phylo/treebase/phylows/study/find?query=tb.identifier.study=17613&format=rss1&recordSchema=tree
Error in function (type, msg, asError = TRUE)  : 
 schannel: CertGetCertificateChain trust error CERT_TRUST_IS_NOT_TIME_VALID

Thank you in advance for anyone's time!

**Comment by aspennington** [comment]
Did anyone find a resolution to this? I got the same error, updated the httr package and updated my CA certificates with no success.

**Comment by jeroen** [comment]
Seems like your server is using a broken SSL certificate. Try [using the openssl backend](https://cran.r-project.org/web/packages/curl/vignettes/windows.html) maybe.
