### ISSUE TITLE
Cannot use the correct curl library on Mac 

### ISSUE THREAD

**Issue by bakaburg1** [jeroen/curl#308]
Hello,

I'm losing my sanity a bit with this.

I needed to access an sftp server, but Mac OS default curl does not have sftp anymore. After some trouble I was able to install it with libssh support via homebrew. In my terminal:
```
curl --version

curl 8.2.1 (aarch64-apple-darwin22.4.0) libcurl/8.2.1 (SecureTransport) OpenSSL/3.1.2 zlib/1.2.11 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libssh2/1.11.0 nghttp2/1.55.1 librtmp/2.3 OpenLDAP/2.6.6
Release-Date: 2023-07-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

then in R I added the new curl to the path: 
```r
Sys.setenv(PATH = paste0("/opt/homebrew/opt/curl/bin:", Sys.getenv("PATH")))
```
I reinstalled both RCurl and curl from source, and now RCurl has sftp support but curl does not. What is missing to link curl to the proper library?

Thanks

**Comment by jeroen** [comment]
First, `RCurl` is an old R package unrelated to this repository, that is no longer maintained. You need the `curl` R package.

Can you try:

```r
Sys.setenv(PKG_CONFIG_PATH="/opt/homebrew/opt/curl/lib/pkgconfig")
install.packages("curl", type = "source")
```

And then you can try

```r
curl::curl_version()
```

**Comment by bakaburg1** [comment]
Thanks! yes, I mentioned RCurl just to show that I was able to have sftp in at least one of the two packages.

**Comment by bakaburg1** [comment]
Sorry to bother but I'm curious. Is PKG_CONFIG_PATH specific to your package, or do other packages share it too?

**Comment by jeroen** [comment]
It is used by the `pkg-config` utility, which is available on all linux/unix systems to find system libraries. You can easily google this.

**Comment by jeroen** [comment]
Did this fix your problem? If not, can you share the full output of `install.packages("curl", type = 'source')` ?

**Comment by bakaburg1** [comment]
Yes, it did! No need for more actions!
