### ISSUE TITLE
can not install curl Rpackage

### ISSUE THREAD

**Issue by lizhan96** [jeroen/curl#310]
error message:

> Error: package or namespace load failed for ‘curl’ in dyn.load(file, DLLpath = DLLpath, ...):
>  unable to load shared object '/usr/local/lib/R/site-library/00LOCK-curl/00new/curl/libs/curl.so':
>   /usr/local/lib/R/site-library/00LOCK-curl/00new/curl/libs/curl.so: undefined symbol: curl_easy_option_next
> Error: loading failed
> Execution halted
> ERROR: loading failed
> * removing ‘/usr/local/lib/R/site-library/curl’

I have installed the curl dev in linux

> root@4e3678ff2024:/# curl --version
> curl 8.2.1 (x86_64-pc-linux-gnu) libcurl/8.2.1 zlib/1.2.11
> Release-Date: 2023-07-26
> Protocols: dict file ftp gopher http imap mqtt pop3 rtsp smtp telnet tftp
> Features: alt-svc AsynchDNS IPv6 Largefile libz threadsafe UnixSockets
>

**Comment by jeroen** [comment]
You have multiple conflicting versions of libcurl on your machine. Try removing the custom one under `/usr/local`:

```sh
sudo rm -Rf /usr/local/include/curl 
sudo rm -Rf /usr/local/lib/libcurl*
```

And instead install the libcurl system library on your machine, such as `yum install curl-devel` or `apt-get install libcurl4-openssl-dev`
