### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle)

### ISSUE THREAD

**Issue by josemanuelgis** [jeroen/curl#311]
I am uploading some raster files with the gcs_upload() function, and for some reason some files generate the following error:

Auto-refreshing stale OAuth token.
Error in curl::curl_fetch_memory(url, handle = handle): HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
Request failed [ERROR]. Retrying in 1 seconds...
Error in curl::curl_fetch_memory(url, handle = handle): HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
Request failed [ERROR]. Retrying in 2.1 seconds...
Error in curl::curl_fetch_memory(url, handle = handle) :
HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
In addition: There were 30 warnings (use warnings() to see them)
Error in value[[3L]](https://github.com/cloudyr/googleCloudStorageR/issues/cond) :
Request failed before finding status code: HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

Thank you very much in advance

**Comment by jeroen** [comment]
It looks like your connections are unstable. Which platform do you use? Does this happen for all servers? One thing that would be worth trying is [disabling http/2](https://cran.r-project.org/web/packages/curl/vignettes/intro.html#Disabling_HTTP2) for the connection, but you need to do that in the R package (googleCloudStorageR). This isn't something we can fix in curl.

**Comment by dsaada** [comment]
Any updates in this?
