### ISSUE TITLE
Do discovered vulnerabilities in curl apply here?

### ISSUE THREAD

**Issue by schuemie** [jeroen/curl#312]
Sorry if this is a stupid question: Do the [recently discovered vulnerabilities in the curl library](https://github.com/curl/curl/discussions/12026) apply to this R package as well? If so, will there be a new release with the patch scheduled for Oct 11?

**Comment by jeroen** [comment]
Probably not, because we don't embed the libcurl source code, we only link to it. So you have to get the new libcurl from your os. An exception may be for Windows where we statically link a copy of curl. We'll see.
