### ISSUE TITLE
Issues with postfieldsize in recent R curl versions

### ISSUE THREAD

**Issue by AntonioFasano** [jeroen/curl#313]
For several years now, I have built my post requests in R curl with (full example ahead):
```R
postfields.opt <- list(post = TRUE, postfields = postfields, postfieldsize = nchar(postfields))
handle_setopt(handle, .list = postfields.opt)
curl_fetch_memory(url, handle = handle)
```

These lines have served me well over the years, and as for `postfieldsize`, according to [libcurl](https://curl.se/libcurl/c/CURLOPT_POSTFIELDSIZE.html):
> If you want to post static data to the server without having libcurl do a strlen() to measure the data size, this option must be used. When this option is used you can post fully binary data, which otherwise is likely to fail. If this size is set to -1, libcurl uses strlen() to get the size or relies on the CURLOPT_READFUNCTION (if used) to signal the end of data. 

As it seems, `postfieldsize` is necessary for binary data and harmless for other type of data.
However, when using curl recently, my POSTs started not working. Specifically, this snippet gives a 400 error:
```R
library('curl')
library('jsonlite')
handle <- new_handle()
postfields <- "key1=value1&key2=value2"
postfields.opt <- list(post = TRUE, postfields = postfields, postfieldsize = nchar(postfields))
handle_setopt(handle, .list = postfields.opt)
resp <- curl_fetch_memory("https://httpbin.org/post", handle = handle)
parse_headers(resp$headers)[1]  # HTTP/2 400 
fromJSON(rawToChar(resp$content))$form # broken
```

Note that replacing the `copypostfields` field for `postfields` does not help, that is:
```R
postfields.opt <- list(post = TRUE, copypostfields = postfields, postfieldsize = nchar(postfields))
```
In fact, in [libcurl](https://curl.se/libcurl/c/CURLOPT_COPYPOSTFIELDS.html), `postfields` is a pointer, so the developer has the responsibility to assure the pointed data integrity until the transfer finishes, and`copypostfields` avoids this by copying the data. However, in R, once you issue a `handle_setopt()`, with POST data, they are passed _by value_, not _by reference_ (unless there is some environment variable involved). 

The error is removed if `postfieldsize` parameter is removed. Therefore, the **correct snippet** is:
```R
library('curl')
library('jsonlite')
handle <- new_handle()
postfields <- "key1=value1&key2=value2"
postfields.opt <- list(post = TRUE, postfields = postfields)
handle_setopt(handle, .list = postfields.opt)
rm(postfields)
rm(postfields.opt)
resp <- curl_fetch_memory("https://httpbin.org/post", handle = handle)
parse_headers(resp$headers)[1]  # HTTP/2 200 
fromJSON(rawToChar(resp$content))$form 

# > $key1
# [1] "value1"
#  
# $key2
# [1] "value2"
```

I have tested this on multiple websites and, given the libcurl docs already [linked](https://curl.se/libcurl/c/CURLOPT_POSTFIELDSIZE.html), I wonder if this is just due to R curl implementation and possibly a bug.
For example, this snippet still using `postfieldsize`, but based on the old RCurl package, works like a charm:
```R
library(RCurl)
library('jsonlite')
postfields <- "key1=value1&key2=value2"
postfields.opt <- list(post = TRUE, postfields = postfields, postfieldsize = nchar(postfields))
resp <- getURL("https://httpbin.org/post", .opts = postfields.opt)
fromJSON(resp)$form
```

Finally, this chunk of code surprisingly works:
```
library('curl')
library('jsonlite')
handle <- new_handle()
postfields <- "key1=value1&key2=value2"
postfields.opt <- list(post = TRUE,  postfieldsize = nchar(postfields), postfields = postfields)
handle_setopt(handle, .list = postfields.opt)
rm(postfields)
rm(postfields.opt)
resp <- curl_fetch_memory("https://httpbin.org/post", handle = handle)
parse_headers(resp$headers)[1]  
fromJSON(rawToChar(resp$content))$form 
```

If your first glance fails you, I have just swapped the order of  `postfields` and `postfieldsize` parameters.
It shouldn't be so, since R users expect `f(x = 1, y = 2)` and `f(y = 2, x = 1)` to return the same output. Maybe the C interface code does not preserve the integrity of the data buffer, as required by libcurl, making them inconsistent with the length. 

I would appreciate any enlightenment on this.

_I am using curl_5.0.0 with libcurl 8.4.0 under Linux._

**Comment by jeroen** [comment]
There is no need in the R bindings to set `postfieldsize` because we know the size of the vector already. What surprises me a bit is that I think there is a bug in libcurl that causes `postfields` to get reset when setting `postfieldsize`, which causes the error.

However the solution is the same, just dont set  `postfieldsize`, we do that for you based on the `postfields` data.

**Comment by jeroen** [comment]
The issue appears because the R bindings normalize `postfields` into `copypostfields` to prevent the data from being garbage collected by R before curl finishes the request. The behavior you see is explained [here](https://curl.se/libcurl/c/CURLOPT_COPYPOSTFIELDS.html):

> Because data is copied, care must be taken when using this option in conjunction with [CURLOPT_POSTFIELDSIZE](https://curl.se/libcurl/c/CURLOPT_POSTFIELDSIZE.html) or [CURLOPT_POSTFIELDSIZE_LARGE](https://curl.se/libcurl/c/CURLOPT_POSTFIELDSIZE_LARGE.html). If the size has not been set prior to [CURLOPT_COPYPOSTFIELDS](https://curl.se/libcurl/c/CURLOPT_COPYPOSTFIELDS.html), the data is assumed to be a null-terminated string; else the stored size informs the library about the byte count to copy. __In any case, the size must not be changed after [CURLOPT_COPYPOSTFIELDS](https://curl.se/libcurl/c/CURLOPT_COPYPOSTFIELDS.html), unless another [CURLOPT_POSTFIELDS](https://curl.se/libcurl/c/CURLOPT_POSTFIELDS.html) or [CURLOPT_COPYPOSTFIELDS](https://curl.se/libcurl/c/CURLOPT_COPYPOSTFIELDS.html) option is set.__

In either case, the solution is the same. Just don't set `postfieldsize` manually and let the R package do this for you.

**Comment by jeroen** [comment]
Note to self:

When using a post from a `readfunction`, we actually do need to set a `postfieldsize`. We just don't need to set it in combination with `copypostfields`.
