### ISSUE TITLE
'Remote file not found' if SMB path has Unicode characters

### ISSUE THREAD

**Issue by niheaven** [jeroen/curl#314]
Hi, when I use `curl_download()` and if the URL has Unicode characters (Chinese here), the output is `Remote file not found` while I could get the file in `curl` CLI. Why and how could I fix it?

The URL I used likes `smb://xxx:xxx@xxx.xxx.xxx/shares/中文/中文2/some_file`

In R:
![image](https://github.com/jeroen/curl/assets/5832170/bd23e513-731e-440b-99fc-bbdb6fed28bf)

In console:
![image](https://github.com/jeroen/curl/assets/5832170/99cf264c-af55-4267-beff-fbf7f7e736bd)

PS: Same host and with English path and file name, the transfer is done correctly.
![image](https://github.com/jeroen/curl/assets/5832170/b4fa37b9-b582-4586-9e25-7b00067a3245)

**Comment by niheaven** [comment]
Any idea?

**Comment by jeroen** [comment]
Can you add 'verbose=TRUE' to the handle?

Op wo 27 dec. 2023 09:26 schreef Hsiao-nan Cheung ***@***.***

**Comment by niheaven** [comment]
![image](https://github.com/jeroen/curl/assets/5832170/307c9ad1-1723-4a78-8c60-6613fae51440)

CJK character and English only, and the file is there.

![image](https://github.com/jeroen/curl/assets/5832170/41263156-e487-4c92-869d-b72d8d8ee564)

**Comment by jeroen** [comment]
Don't use  `URLencode()`. If anything you would use `curl::curl_escape()` but I don't think it is necessary. I think that only works for HTTP requests, and you are using smb.

I don't know smb very well, but I am surprised we don't see more details about about the request with `verbose=TRUE`.

Are you using the latest version of R? Can you show your `sessionInfo()`?

Can you try to `enc2utf8` the url value before passing to curl_fetch_memory?

**Comment by niheaven** [comment]
``` r
library(curl)
#> Using libcurl 8.3.0 with Schannel
handle <- new_handle(username = "MASKED", password = "MASKED", verbose = TRUE)
curl_fetch_memory(paste0("smb://10.86.MASKED/", curl::curl_escape(enc2utf8("新建文本文档.txt"))), handle = handle)
#> Error in curl_fetch_memory(paste0("smb://10.86.MASKED/", : Remote file not found
curl_fetch_memory(paste0("smb://10.86.MASKED/", curl::curl_escape("新建文本文档.txt")), handle = handle)
#> Error in curl_fetch_memory(paste0("smb://10.86.MASKED/", : Remote file not found
curl_fetch_memory(enc2utf8("smb://10.86.MASKED/新建文本文档.txt"), handle = handle)
#> Error in curl_fetch_memory(enc2utf8("smb://10.86.MASKED/新建文本文档.txt"), : Remote file not found
```

<sup>Created on 2023-12-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.2 (2023-10-31 ucrt)
#>  os       Windows 11 x64 (build 26010)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language en
#>  collate  Chinese (Simplified)_China.utf8
#>  ctype    Chinese (Simplified)_China.utf8
#>  tz       Asia/Shanghai
#>  date     2023-12-29
#>  pandoc   3.1.11 @ D:/Scoop/shims/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.6.2   2023-12-11 [1] CRAN (R 4.3.2)
#>  curl        * 5.2.0   2023-12-08 [1] CRAN (R 4.3.2)
#>  digest        0.6.33  2023-07-07 [1] CRAN (R 4.3.1)
#>  evaluate      0.23    2023-11-01 [1] CRAN (R 4.3.2)
#>  fastmap       1.1.1   2023-02-24 [1] CRAN (R 4.3.0)
#>  fs            1.6.3   2023-07-20 [1] CRAN (R 4.3.1)
#>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.3.0)
#>  htmltools     0.5.7   2023-11-03 [1] CRAN (R 4.3.2)
#>  knitr         1.45    2023-10-30 [1] CRAN (R 4.3.2)
#>  lifecycle     1.0.4   2023-11-07 [1] CRAN (R 4.3.2)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.3.0)
#>  purrr         1.0.2   2023-08-10 [1] CRAN (R 4.3.1)
#>  R.cache       0.16.0  2022-07-21 [1] CRAN (R 4.3.0)
#>  R.methodsS3   1.8.2   2022-06-13 [1] CRAN (R 4.3.0)
#>  R.oo          1.25.0  2022-06-12 [1] CRAN (R 4.3.0)
#>  R.utils       2.12.3  2023-11-18 [1] CRAN (R 4.3.2)
#>  reprex        2.0.2   2022-08-17 [1] CRAN (R 4.3.0)
#>  rlang         1.1.2   2023-11-04 [1] CRAN (R 4.3.2)
#>  rmarkdown     2.25    2023-09-18 [1] CRAN (R 4.3.1)
#>  rstudioapi    0.15.0  2023-07-07 [1] CRAN (R 4.3.1)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.3.0)
#>  styler        1.10.2  2023-08-29 [1] CRAN (R 4.3.1)
#>  vctrs         0.6.5   2023-12-01 [1] CRAN (R 4.3.2)
#>  withr         2.5.2   2023-10-30 [1] CRAN (R 4.3.1)
#>  xfun          0.41    2023-11-01 [1] CRAN (R 4.3.2)
#>  yaml          2.3.8   2023-12-11 [1] CRAN (R 4.3.2)
#> 
#>  [1] D:/Scoop/persist/r/site-library
#>  [2] D:/Scoop/apps/r/4.3.2/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>


The error message is the same as above.

**Comment by niheaven** [comment]
Hmm, I think it's bug of `libcurl`, not the `curl` package. Since I've tried `download.file("smb://xxx", method = "libcurl")` and met the same error.

**Comment by jeroen** [comment]
I don't think there is much we can do in the R bindings. Better follow up in the libcurl bug tracker or mailing list.
