### ISSUE TITLE
Error in curl::handle_setopt(handle, .list = req$options): Option seekfunction (20167) has unknown or unsupported type.

### ISSUE THREAD

**Issue by lgnbhl** [jeroen/curl#315]
Hello,

I got an error from the curl package using the function `cr_deploy_run()` from the googleCloudRunner R package. The maintainer asked me to follow the discussion here (so here I am 😊). https://github.com/MarkEdmondson1234/googleCloudRunner/issues/208

``` r
Error in curl::handle_setopt(handle, .list = req$options): Option seekfunction (20167) has unknown or unsupported type.
```

Any idea how to fix this?

Thanks a lot!
Félix

**Comment by jeroen** [comment]
I am guessing your `curl` is outdated. Can you do `install.packages("curl")` and try again.

**Comment by LynnChan99** [comment]
> I am guessing your `curl` is outdated, because this is something we added recently. Can you do `install.packages("curl")` and try again?
> 
> If this does not help, can you give me your `sessioninfo()` and `curl::curl_version()` ?

Hi, I have tried to reupdate and reinstall the curl package, but this error seems can't be fixed:

Error in curl::handle_setopt(handle, .list = req$options) : 
  Invalid or unsupported value when setting curl option 'timeout_ms'

**Comment by jeroen** [comment]
@LynnChan99 what code are you using to get this error?

**Comment by LynnChan99** [comment]
> [@LynnChan99](https://github.com/LynnChan99) what code are you using to get this error?

Hi, it's 'sce_T <- RunAzimuth(sce_T, reference = "pbmcref")'
