### ISSUE TITLE
form_data documentation is lacking

### ISSUE THREAD

**Issue by jangorecki** [jeroen/curl#316]
`form_data` seems to be rather poorly documented.
There are no examples in `?form_data`. "intro" vignette doesn't present its use either.
I think it would be beneficial to improve documentation on that.

**Comment by jeroen** [comment]
There have been examples of `form_data` in the intro vignette for at least 7 years:

![Screenshot 2024-10-24 at 10 01 14 pm](https://github.com/user-attachments/assets/d6a46546-8587-4cf7-a89c-faa4a5d0dbc5)
