### ISSUE TITLE
parse_headers throws an error when a site responds with an empty header

### ISSUE THREAD

**Issue by pepijn-devries** [jeroen/curl#317]
Thanks for your work on `curl`! Some sites (e.g. sftp sites) respond with an empty header (`raw(0)`). When this is parsed with `parse_headers`, an error is thrown. Would it be possible to return an empry vector (e.g., `character(0)`) instead?

``` r
library(curl)
#> Using libcurl 7.64.1 with Schannel

parse_headers(raw(0))
#> Error in headers[[length(headers)]]: attempt to select less than one element in integerOneIndex
```

<sup>Created on 2023-11-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

If you are wondering why I would want to parse an empty header: I don't necesarrily. I'm using `httr2`, where `req_perform` calls this parser and breaks on sites which respond with an empty header.

**Comment by jeroen** [comment]
I think you are using an old version of curl. This seems to be fixed already in the latest releases.

**Comment by pepijn-devries** [comment]
My apologies. You are right. Before I was using `curl_4.3.2` after installing `curl_5.1.0` the issue was fixed.
