### ISSUE TITLE
Allow users to pass pool object in `multi_download()`

### ISSUE THREAD

**Issue by gacolitti** [jeroen/curl#322]
`multi_download()` is a very nice wrapper, but it currently does not allow users to pass a pool object directly. This means users have to use the default pool parameters, which may not be suitable for every use-case.

To solve this issue we could replace the `multiplex` argument with a `pool` argument.

**Comment by jeroen** [comment]
I'm not convinced this is needed. The only other pooling parameter is the number of concurrent connections, but I think it makes sense to use the default. A browser also does not let you configure the number of connections per host.
