### ISSUE TITLE
How to resolve "SSL: no alternative certificate subject name matches target host name '<proxy.server.address>'"

### ISSUE THREAD

**Issue by ng-yingjie** [jeroen/curl#326]
I cannot complete a curl command without running into the following error (the host name is a proxy server):
![image](https://github.com/jeroen/curl/assets/51477000/2186e31e-2189-4d03-8ce3-183dfbad3a2e)

I run R3.5.3 on a RHEL7 server and it has to go through a proxy due to organisation security reasons. I have updated all my CA certificates and all the related softwares in RHEL. I tried setting verifypeer and verifyhost to 'FALSE' but none worked.

Strangely, the curl command does work on my Linux command line but not within my R environment.

Would appreciate any tips/help, thank you in advance!

**Comment by jeroen** [comment]
For proxy servers you may have to enable additional options, see `curl::curl_options('proxy')` what is available. You may also have to enable variables like `ALL_PROXY` see https://everything.curl.dev/usingcurl/proxies/env.html.

Either way RHEL-7 is EOL now. Feel free to open a new issue if this happens for other systems, but please do try to include more details on options that you use to authenticate with the proxy server, and a `verbose` http request.
