### ISSUE TITLE
Sudden negotiate error with 5.2.1

### ISSUE THREAD

**Issue by vedoa** [jeroen/curl#334]
Since the release of the 5.2.1 something similar to what was reported here https://github.com/curl/curl/issues/12112#issue-1941771424 happens trying to use gssnegotiate for authorization. The error happens every time i call the code bellow: 
```r
library(curl)
h <- new_handle()
handle_setopt(h,
             .list = list(followlocation = T,
                          userpwd = ":",
                          httpauth = 4,
                          verbose = T
             )
)
handle_setheaders(h,
                  "Accept" = "text/plain",
                  "User-Agent" = "rawcurl")

d <- curl_fetch_memory(url = "https://redactedurl", handle = h)
rawToChar(d$content)
```
Error:
```
* WARNING: failed to open cookie file ""
*   Trying 172.28.127.110:443...
* Connected to redactedurl (172.28.127.110) port 443
* schannel: disabled automatic use of client certificate
* using HTTP/1.x
* Server auth using Negotiate with user ''
```
Since the client certificates are disabled on the initial call every further redirect fails (which is the desired behavior).
For every other curl version including 5.2.0 i get 
```
*   Trying 172.28.127.110:443...
* TCP_NODELAY set
* Connected to redactedurl (172.28.127.110) port 443 (#0)
* Server auth using Negotiate with user ''
```
as expected.
I am aware that this is very hard to reproduce - but if someone experienced something similar it would be great to get some inputs how to solve it.
As i mentioned, every other version, including 5.2.0, works as expected - no warning for the cookie file - certificates work as expected - re-directions are followed.

**Comment by jeroen** [comment]
I think this is because we disabled `CURLOPT_UNRESTRICTED_AUTH` in 5.2.1. See https://github.com/jeroen/curl/issues/260.

You can try to re-enable this option in your handle to get the old behavior?

**Comment by vedoa** [comment]
@jeroen confirming that your suggestion is right. Thank you.
For reference the handle option

```r
handle_setopt(h,
             .list = list(followlocation = T,
                          userpwd = ":",
                          httpauth = 4,
                          unrestricted_auth = T, # CURLOPT_UNRESTRICTED_AUTH
                          verbose = T
             )
)
```
