### ISSUE TITLE
stubbed version for (non)use in webr installs requiring curl

### ISSUE THREAD

**Issue by timelyportfolio** [jeroen/curl#337]
`curl` is amazing and fantastic which means there are thousands of reverse dependencies with R packages.  Since `curl` is not available in `webr`, all of these packages are rendered unavailable in `webr`.  Many of these packages require `curl` when in reality `curl` is not necessary for most of the core functionality.  I thought what if we could have a stubbed useless but installable `curl` only for the purposes of `webr`, so I forked and have https://github.com/timelyportfolio/curl that I think can serve this purpose.  I think `shinylive` has some sort of mechanism to do something similar, but I have not yet been able to understand how this mechanism works or if it could be leveraged in non-shinylive contexts.

Would it mess you up if I add my stubbed `curl` to my r-universe to test to see if we can unlock packages by installing this useless version of `curl` before attempting to install the r-universe Emscripten build of packages that require but really optionally depend on `curl`?  Feel free to tell me no.

Thanks for all your amazing work!!

**Comment by jeroen** [comment]
In your own r universe you can try whatever you want, it's your space :-) But ideally I think we should try to implement at least some of this for emscripten using the fetch api: https://emscripten.org/docs/api_reference/fetch.html

**Comment by timelyportfolio** [comment]
Thanks so much.  I tried it, but I get failures on r-universe docs build since the stubbed `curl` package is installed then the documentation builds fail :(

I guess I'll try to build an `install_github` for webr since I do not think there is any way to avoid this step on r-universe.

**Comment by timelyportfolio** [comment]
Wasn't thinking and could/should have just built my own mini repo with instructions at https://r-wasm.github.io/rwasm/articles/github-actions.html instead.  I have removed from r-universe to proceed with this much better option.  For anyone that wants to use this stubbed version in `webr`, here is the command to install and hopefully unlock even more packages:

```
webr::install("curl", repos = "https://timelyportfolio.github.io/webr_repo/")
```

Thanks again for all that you do and sorry to bother you!
