### ISSUE TITLE
Multipart element from raw vector but with filename

### ISSUE THREAD

**Issue by Arthur-Zestco** [jeroen/curl#339]
Hoi Jeroen,

as I read data from one api gateway and try and write it to a different one, I am trying to compose a multipart header whose content come from a raw vector, but that also has a filename as it represents a file attachment. I do not have any local data files to 'upload', so I was looking at using `form_data` to add the element to the header. Unfortunately, looking in the docs and the function formals, I cannot see any way to stipulate the `filename=` in the Content Disposition of the resulting element.

I see how I could write the data to a local file, and use `form_file` to turn that into a multipart element. However, that strikes me as inefficient, inelegant, and possibly even insecure.

Can you think of any way, perhaps low-level manipulation, that I could use to add the filename attribute to the content disposition header after creating the element with form_data?

I appreciate all the work you have put into this fundamental package.
Thanks, Art

**Comment by jeroen** [comment]
Thanks for the suggestion. But the easiest way to set the filename attribute is indeed using the `form_file()` function. This is not insecure at all, just:

```r
tmp <- tempfile()
writeBin(vec, tmp)
form_file(tmp, name = 'myfile.xyz')
```

The code for setting form data/file fields is already pretty messy, I don't think it is worth to add this special case where you want to use raw data as if it were a file, if there is already a way to do this. Thanks for the idea though.
