### ISSUE TITLE
Delete a file from my SFTP server using a custom request?

### ISSUE THREAD

**Issue by lefkiospaikousis** [jeroen/curl#342]
Hello,
Thanks for this great package!

We have been using this package for all sorts of operations (upld, dnld, create directory, emails, etc..)  but we stumbled upon `deletion`

I am trying to delete a file on an SFTP server using a `customrequest` but I fail

PackageVersion('curl'): # 5.2.0    
```
curl::curl_fetch_memory(
  url = "sftp://username:password@server-ip-address", 
  handle = curl::new_handle() |> 
    curl::handle_setopt(
      verbose = TRUE,
      customrequest = "rm files/my_file.txt"
    )
  
)

```

I also tried using `customrequest = "DELETE files/my_file.txt"` but nothing

To check if it works in the command line tool `curl`

In `Powershell`, the below works fine

```
curl sftp://username:password@server-ip-address -Q 'rm files/my_file.txt'
```

Any help would be appreciated 

(Note; apologies for the cross-post from [here](https://stackoverflow.com/questions/78514314/how-can-i-delete-a-file-from-my-sftp-server-using-the-curl-package-in-r), I could not get an answer there)

Lefkios

**Comment by jeroen** [comment]
I haven't tested this, but did you try making the file path of the URL instead of the command?

Does it work with scp intead? Something like:

```r
curl::curl_fetch_memory(
  url = "sftp://username:password@server-ip-address/files/my_file.txt", 
  handle = curl::new_handle() |> 
    curl::handle_setopt(
      verbose = TRUE,
      customrequest = "rm"
    )
)

```

**Comment by jeroen** [comment]
I tested this locally, and I think the problem is we have to use the [quote option](https://curl.se/libcurl/c/CURLOPT_QUOTE.html) instead of `customrequest`. Could you try if this works for you:

```r
curl::curl_fetch_memory(
  url = "sftp://username:password@server-ip-address", 
  handle = curl::new_handle() |> 
    curl::handle_setopt(
      verbose = TRUE,
      quote = "rm files/my_file.txt"
    )
)
```

Btw I tried this with a local ssh-agent so I don't specify any `username:password` in my R code.

**Comment by lefkiospaikousis** [comment]
Yes! with `quote` it works!

(Yes, indeed the `username:password` is not needed in the `url` specification, It can be added inside the `curl::curl_options()`

```
curl::curl_fetch_memory(
  url = "sftp://server-ip-address", 
  handle = curl::new_handle() |> 
    curl::handle_setopt(
     userpwd = username:password
      verbose = TRUE,
      quote = "rm files/my_file.txt"
    )
  
)
```

Many thanks again
