### ISSUE TITLE
Schannel: CertGetCertificwteChain trust error CERT_TRUST_REVOCATION_STATUS_UNKNOWN

### ISSUE THREAD

**Issue by rishirj75** [jeroen/curl#345]
Hello,  i am trying to clone repository in visual studio which is located inside the azure vm 
I dont have any issue doing this outside the vm however in vm i get this error, i am able to open the girhub url in the browser from vm
![17252472618494825724562234084132](https://github.com/user-attachments/assets/bdca7f75-e378-4a64-97ec-837436f127a8)

**Comment by jeroen** [comment]
Please include code that you use and platform information.

**Comment by rishirj75** [comment]
> Please include code that you use and platform information.

Hello Jeroen,  i am just trying to clone the repository and have it in visual studio located in a windows server os in azure vm. 
There is no code written yet
