### ISSUE TITLE
Inconsistent file paths returned from `multi_download` when resumed.

### ISSUE THREAD

**Issue by h-a-graham** [jeroen/curl#346]
Hello, 

Firstly, thanks for this package it is hugely appreciated! 

I recently noticed that when using `curl::multi_download` the destfile column of the returned data.frame object differs depending on whether the file is resumed on completed on first go. When a file is resumed, the destfile is absoloute but when it completes in one it is relative. See here for a reprex: 

``` r
suppressPackageStartupMessages({
  library(curl)
  library(R.utils)
})

# Example: some large files
urls1 <- sprintf(
  "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-%02d.parquet", 1:2
)

# cancel download after 5 seconds
res1 <- try(withTimeout(multi_download(urls1, resume = TRUE), timeout = 5)) # You can interrupt (ESC) and resume
# now escape the download and resume
res1 <- multi_download(urls1, resume = TRUE)

urls2 <- sprintf(
  "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-%02d.parquet", 3:4
)
# Do not escape this.
res2 <- multi_download(urls2, resume = FALSE) # You can interrupt (ESC) and resume

# full filepaths returned when resumed
print(res1$destfile)
#> [1] "/tmp/RtmpbPZ3Zs/reprex-146af8714e091d-awake-topi/yellow_tripdata_2021-01.parquet"
#> [2] "/tmp/RtmpbPZ3Zs/reprex-146af8714e091d-awake-topi/yellow_tripdata_2021-02.parquet"
# relative filepaths returned when completed in one go.
print(res2$destfile)
#> [1] "yellow_tripdata_2021-03.parquet" "yellow_tripdata_2021-04.parquet"
```

<sup>Created on 2024-09-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Is the solution perhaps as simple as setting destfiles to `normalizePath(destfiles,
  mustWork = FALSE
)` in:
https://github.com/jeroen/curl/blob/master/R/multi_download.R#L186

Cheers, 
Hugh

**Comment by jeroen** [comment]
The reason is that the initial `ormalizePath(destfiles, mustWork = FALSE )` returns the full path for files that already exist, and otherwise just the input. Your solution sounds fine to me.
