### ISSUE TITLE
Ominous NOTE on CRAN "Found non-API call to R: ‘R_new_custom_connection’"

### ISSUE THREAD

**Issue by pepijn-devries** [jeroen/curl#347]
Hi there,

On CRAN I saw the ominous NOTE "Found non-API call to R: ‘R_new_custom_connection’" with a warning that this needs to be fixed before 2024-10-04. Is this something that can be fixed, and will 'curl' still be available from CRAN? There are quite a few packages depending on curl.

Cheers,

Pepijn

**Comment by jeroen** [comment]
This deadline is about another NOTE (the fact that `checking tests ... ` prints some noise to the output.

**Comment by pepijn-devries** [comment]
Phew! Glad to hear that. Otherwise, it could have had some major consequences ;).
