### ISSUE TITLE
FTP crashses in libcurl 8.5.0 - 8.7.1

### ISSUE THREAD

**Issue by jeroen** [jeroen/curl#348]
There is [a bug](https://github.com/curl/curl/issues/13731) in libcurl versions 8.5.0 - 8.7.1 with ftp downloads. These versions of libcurl are common on Linux and MacOS systems.

```r
library(curl)
curl_fetch_memory("https://en.wikipedia.org/wiki/Bioconductor")
url2 <- "ftp://ftp.ensembl.org/pub/release-71/gtf/caenorhabditis_elegans/Caenorhabditis_elegans.WBcel235.71.gtf.gz"
response2a <- curl_fetch_memory(url2)
response2b <- curl_fetch_memory(url2)

```

**Comment by jeroen** [comment]
Disabling connection re-use for FTP requests: https://github.com/jeroen/curl/commit/d8b0c7875da20057e13d831bef0e9f90ab8c7463

(we had more issues in the past with this)

**Comment by jeroen** [comment]
Workaround is on CRAN now in curl 6.0.0. To emphasize, the problem also disappears when your system updates to libcurl 8.8.0 or newer.

**Comment by adamhsparks** [comment]
ha! I wasn't crazy, https://github.com/jeroen/curl/issues/338. Thanks for getting this fixed.
