### ISSUE TITLE
Install failed in Centos7 with compilation failed

### ISSUE THREAD

**Issue by SiberiaBlue** [jeroen/curl#353]
<img width="883" alt="image" src="https://github.com/user-attachments/assets/5eab30aa-10c7-4745-895b-73942a670f71">

In file included from handle.c:1:
handle.c: In function ‘make_info_http_version’:
handle.c:424:36: error: ‘CURLINFO_HTTP_VERSION’ undeclared (first use in this function); did you mean ‘CURLOPT_HTTP_VERSION’?
curl-common.h:13:34: note: in definition of macro ‘assert’
handle.c:424:36: note: each undeclared identifier is reported only once for each function it appears in
curl-common.h:13:34: note: in definition of macro ‘assert’
handle.c:429:8: error: ‘CURL_HTTP_VERSION_2_0’ undeclared (first use in this function); did you mean ‘CURL_HTTP_VERSION_1_0’?
handle.c: In function ‘make_handle_response’:
handle.c:494:51: error: ‘CURLINFO_SCHEME’ undeclared (first use in this function); did you mean ‘CURLINFO_FILETIME’?

R version 4.4.1 (2024-06-14)
gcc version 11.2.1 20220127 (Red Hat 11.2.1-9) (GCC) 
curl 8.11.0 (x86_64-unknown-linux-gnu) libcurl/8.11.0 zlib/1.2.13

Has anything I have not install?
Thanks for any help!

**Comment by jeroen** [comment]
You report you are using `curl 8.11.0` but your error suggests you are using the curl version from CentOS7 which is very old.

Can you try `sudo dnf remove curl-devel` to remove the curl from CentOS?

**Comment by SiberiaBlue** [comment]
I known my curl version is too old. So I download the package curl-8.11.0.tar.gz from website and install it. Because it is dependent on higher version openssl. I can only configure it without ssl.

`./configure --prefix=/usr/local/curl --without-ssl --without-libpsl`

Then I see your suggestion, remove my libcurl-devel.

`yum remove libcurl-devel.x86_64`

When I installed curl in R CMD again, fail as expected.

** using staged installation
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing 'libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing 'libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Found INCLUDE_DIR and/or LIB_DIR!
Using PKG_CFLAGS=-I/usr/local/curl/lib/pkgconfig/libcurl.pc 
Using PKG_LIBS=-L/usr/local/curl/lib/pkgconfig/libcurl.pc -lcurl
--------------------------- [ANTICONF] --------------------------------
Configuration failed because libcurl was not found. Try installing:
 *\ deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 *\ rpm: libcurl-devel (Fedora, CentOS, RHEL)
If libcurl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libcurl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
cc1: warning: /usr/local/curl/lib/pkgconfig/libcurl.pc: not a directory

But I have actually installed the height version curl. I try to search libcurl from pkg-config. It is not found.

`pkg-config --libs libcurl`
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found

Now I probably known what's going wrong. And I update my pkg-config config path.

`find / -name "libcurl.pc"`
/usr/local/curl-8.11.0/libcurl.pc
/usr/local/curl/lib/pkgconfig/libcurl.pc

`vi ~/.bashrc`
export PKG_CONFIG_PATH=/usr/local/curl/lib/pkgconfig
export PATH=$PKG_CONFIG_PATH:$PATH
`source ~/.bashrc`

Then install curl, it's successfully!!

`install.packages("curl")`

** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-I/usr/local/curl/include  
Using PKG_LIBS=-L/usr/local/curl/lib -lcurl  
Found recent recent version of libcurl
** libs
using C compiler: ‘gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)’
rm -f curl.so callbacks.o curl.o download.o escape.o fetch.o findport.o form.o getdate.o handle.o ieproxy.o init.o interrupt.o multi.o nslookup.o options.o reflist.o split.o ssl.o typechecking.o urlparser.o utils.o version.o winidn.o writer.o
...
installing to /usr/local/lib64/R/library/00LOCK-curl/00new/curl/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
DONE (curl)

Thanks for your help!

**Comment by jeroen** [comment]
I don't think curl without openssl is helpful, you won't be able to make https connections.
Maybe also install build openssl.

**Comment by SiberiaBlue** [comment]
> I don't think curl without openssl is helpful, you won't be able to make https connections. Maybe also install build openssl.

In fact, I need to install curl, because I need to use 'gggenes' to draw a gene arrows pic, whitch is dependent on curl.
Maybe it will use curl to do something soon, fortunately it's not today, haha.
Have a nice day!
