### ISSUE TITLE
MacOS: package or namespace load failed - Symbol not found: _curl_easy_option_by_id

### ISSUE THREAD

**Issue by Khalifa449** [jeroen/curl#360]
I'm trying to download the Quantmod package, but it needs other packages for it to work. One of those packages is Curl. Some files don't load when downloading the package. The packages download normally, but when you run them/use them they don't. The error message is below. 

1) library(quantmod) Error:

Loading required package: xts
Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

Loading required package: TTR
Error: package or namespace load failed for ‘TTR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library/curl/libs/curl.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library/curl/libs/curl.so, 6): Symbol not found: _curl_easy_option_by_id
  Referenced from: /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library/curl/libs/curl.so
  Expected in: /usr/lib/libcurl.4.dylib
 in /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library/curl/libs/curl.so
Error: package ‘TTR’ could not be loaded

2) Library(TTR) Error:

Error: package or namespace load failed for ‘TTR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library/curl/libs/curl.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library/curl/libs/curl.so, 6): Symbol not found: _curl_easy_option_by_id
  Referenced from: /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library/curl/libs/curl.so
  Expected in: /usr/lib/libcurl.4.dylib
 in /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library/curl/libs/curl.so

3) libray(curl) Error: 

Error: package or namespace load failed for ‘curl’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library/curl/libs/curl.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library/curl/libs/curl.so, 6): Symbol not found: _curl_easy_option_by_id
  Referenced from: /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library/curl/libs/curl.so
  Expected in: /usr/lib/libcurl.4.dylib
 in /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library/curl/libs/curl.so

**Comment by jeroen** [comment]
Can you check: https://github.com/jeroen/curl/issues/358#issuecomment-2495635893

**Comment by Khalifa449** [comment]
Yes, my Mac was working on MacOS 11, and that was outdated. Thank you so much.
