### ISSUE TITLE
make_string(LIBCURL_VERSION) fails clang's Wstring-conversion

### ISSUE THREAD

**Issue by MichaelChirico** [jeroen/curl#361]
https://github.com/jeroen/curl/blob/ae452a8dd326fd49daf8e1352fbd4da8a8f05a77/src/version.c#L10

Gives compilation failure on clang (https://clang.llvm.org/docs/DiagnosticsReference.html#wstring-conversion):

```
src/version.c:10:39: error: implicit conversion turns string literal into bool: 'char[11]' to '_Bool' [-Werror,-Wstring-conversion]
   10 |   SET_VECTOR_ELT(list, 1, make_string(LIBCURL_VERSION));
      |                           ~~~~~~~~~~~~^~~~~~~~~~~~~~~~
$PATH/curl/src/include/curl/curlver.h:35:25: note: expanded from macro 'LIBCURL_VERSION'
   35 | #define LIBCURL_VERSION "8.10.1-DEV"
      |                         ^~~~~~~~~~~~
src/curl-common.h:11:24: note: expanded from macro 'make_string'
   11 | #define make_string(x) x ? Rf_mkString(x) : Rf_ScalarString(NA_STRING)
      |                        ^ ~
```

This looks reasonable to me -- char literal on LHS of `?` looks questionable. I haven't read all the other uses of `make_string()` carefully enough, but maybe something like

```c
#define make_string(x) x!=NULL && x ? Rf_mkString(x) : Rf_ScalarString(NA_STRING)
```

Would be better? That compiles for me. Maybe just `x != NULL ? ...` is enough.

**Comment by jeroen** [comment]
Is this a new clang flag? I'm not seeing this error on clang 19.

**Comment by MichaelChirico** [comment]
I can't say for sure... I do see references to it at least 4 years old:

https://github.com/llvm/llvm-project/commit/637b9332020ed2b24ceae4ec37e2aa1e41ec086a

Did you compile it specifically with `-Wstring-conversion` set?
