### ISSUE TITLE
Curl connection open() can't be interrupted

### ISSUE THREAD

**Issue by jcheng5** [jeroen/curl#363]
We make heavy use of `curl::curl()` in [ellmer](https://github.com/tidyverse/ellmer). Sometimes when the LLM APIs get slow, it puts the R session in an uninterruptible hang.

## Repro steps

First, have some way of listening on a port but never actually responding to the request. I used netcat:

```
nc -lk localhost 4321
```

or in R:

```r
httpuv::runServer("127.0.0.1", 4321, list(
  call = function(req) {
    Sys.sleep(Inf)
  }
))
```

Then run this code in a different R session:

```r
con <- curl::curl("http://localhost:4321")
open(con)
```

and try to Ctrl+C.

**Comment by jeroen** [comment]
I modified it a bit to reset the connection before the jump. Please lmk if this seems to work for you.

**Comment by jcheng5** [comment]
@jeroen Works great, thank you!
