### ISSUE TITLE
Flexible URL parse?

### ISSUE THREAD

**Issue by hadley** [jeroen/curl#368]
I'm not sure what's going on here. `curl httpbin.org` works, but:

``` r
curl::curl_parse_url("httpbin.org")
#> Error in curl::curl_parse_url("httpbin.org"): Failed to parse URL: Bad scheme
```

<sup>Created on 2024-12-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by jeroen** [comment]
That is by design. A url has to start with `scheme://` so we require that. The `curl` command line is a bit more lenient and guesses `https` to be the scheme in case no scheme is given, but it's really safer to require it explicitly.

**Comment by jeroen** [comment]
We could make it opt-in, but the problem is also that this makes the
behaviour inconsistent with the ada fallback parser. So it depends a bit in
how portable this has to be.

Op di 24 dec 2024 17:49 schreef Hadley Wickham ***@***.***>:
