### ISSUE TITLE
Test for busy waiting

### ISSUE THREAD

**Issue by jeroen** [jeroen/curl#83]
See https://github.com/jeroenooms/curl/commit/52dd3249bf3612c0a824ee7c8ab9137b93007307. Make sure we are not using 100% CPU when waiting.

**Comment by gaborcsardi** [comment]
There are a number of ways we could try. E.g. 
* checking actual processor usage
* checking that the process is waiting for I/O (from another process)

Probably the first is easiest, e.g.
```r
system.time(res <- curl_fetch_stream("http://httpbin.org/delay/5", function(x) { }))
```
should return close to zero `user` and `system` time. E.g. with `curl` version 2.3 we get
```
   user  system elapsed
  1.626   3.628   5.262
```
and with 2.7 we get
```
   user  system elapsed
  0.490   0.002   5.811
```

That half a second is still suspicious, I guess that it is still busy waiting a little bit? I don't always get it, though, sometimes it is good.

Anyway, I guess sg. like this could serve as a test case. I would probably turn it off on CRAN, though.
