### ISSUE TITLE
Unable to run curl in a loop

### ISSUE THREAD

**Issue by kds15e** [jeroen/curl#92]
Hi there,

I am accessing the Global Names Recognition and Discovery API (http://gnrd.globalnames.org/) using curl, which requires calling two urls in succession: first the search url, then the token url (which is taken from the results of calling the search url). Then I parse the results of the token url to extract scientific names. All of this is successful if I run the script once. However, running the code within a loop (i.e. performing this for a list of search urls) is unsuccessful: the first search url doesn't even run. I have tried closing the connections after I've extracted the necessary information (within the loop), but this hasn't fixed the issue. Could it be that R is calling the URL too quickly? I'm at a loss...

Thanks!

**Comment by jeroenooms** [comment]
Please include example code that exemplifies the problem.

**Comment by kds15e** [comment]
`##some set up code before this
#url2fetch is the list of URLs to call
for(i in 1:length(url2fetch)){
  scinames=c() #soon-to-be array of scientific names
  url=url(url2fetch[i],open="r") #call the search URL
  results=readLines(url)
  close(url)
  results=gsub("  <token_url>","",results[5]) #Clean up line 5 to get the token URL
  results=gsub("</token_url>","",results)
  second.url=url(results,open="r") #Call the token URL
  second.results=readLines(second.url)
  close(second.url)
###then there are further step to output scinames in a useful way'
