### ISSUE TITLE
curl  through proxy

### ISSUE THREAD

**Issue by fredoh91** [jeroen/curl#94]
I try to use your curl through a proxy, I try some things to set this parameter, but I can't succeed in.

Can you help me, for setting this value, please ?

I'm behind a http proxy (as http://xxxxx.fr) , on the 8080 port

I have the following error message 

> con <- curl("https://httpbin.org/get")
> readLines(con)
Error in readLines(con) : Couldn't connect to server

best regards

Fred

**Comment by jeroen** [comment]
You need to set the [CURLOPT_PROXY](https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html) option in your handle:

```r
h <- new_handle(proxy = "http://xxxxx.fr:8080")
con <- curl("https://httpbin.org/get", handle = h)
```

You might also have a look at the `httr` package which wraps around this package and provides a convenient `use_proxy()` function.
