### ISSUE TITLE
Error in curl_download(url, dsn, handle = h) : Transferred a partial file

### ISSUE THREAD

**Issue by mgageo** [jeroen/curl#97]
Hello,

I try to download with success a lot of files.
On the biggest file (> 15 Mo), I have this error : _Error in curl_download(url, dsn, handle = h) : Transferred a partial file_
How can i change options like RESUME_FROM MAXSIZE ?
Marc

**Comment by jeroen** [comment]
Try [reading the documentation](https://cran.r-project.org/web/packages/curl/vignettes/intro.html#configuring_a_handle).
