### ISSUE TITLE
CRAN error for mac with R 3.3

### ISSUE THREAD

**Issue by vnijs** [jeroen/curl#98]
Hoi Jeroen,

A test fails on mac and curl version 2.5 is not available for mac (see cran link below). Happy to test in case you don't have access to OSX with R-3.3

https://cran.r-project.org/web/checks/check_results_curl.html

mvg Vincent

**Comment by jeroen** [comment]
I've tested this myself on OSX 10.9 but the test doesn't fail. It seems like some server configration problem :/ I guess I'll just disable that unit test.

**Comment by vnijs** [comment]
Hmmm. Tests actually run fine on El-Capitan with R-3.3 as well. I listed curl 2.5 in 'depends' so I was getting an error on CRAN as well :)

**Comment by jeroen** [comment]
I'll fix this asap.

**Comment by jeroen** [comment]
Fixed @ https://github.com/jeroen/curl/commit/c1c85d431ab9ad08d986ee9dc8850fdee33ea04d.

**Comment by vnijs** [comment]
Bedankt!

**Comment by jeroen** [comment]
This is now fixed on ze cran.
