### ISSUE TITLE
Can cause segfault by passing empty function as handle argument

### ISSUE THREAD

**Issue by joshuaulrich** [jeroen/curl#99]
Yes, I know this is a really dumb thing to do... but I managed to do it.  I personally consider all crashes as bugs in my code, so I wanted to let you know about it.

Here are two reproducible examples that will bring down your R session, using the latest commit from the master branch.

```r
#curl::curl_download("https://www.google.com", tempfile(), handle=function(){})
#curl::curl_fetch_memory("https://www.google.com", handle=function(){})
```

**Comment by jeroen** [comment]
Fixed @ https://github.com/jeroen/curl/commit/47fad0da6a01f6e23cf0dfb72b09709ce9defaa0. Thanks. :)
